CREATE SCHEMA IF NOT EXISTS iobeam_admin;
SET search_path TO iobeam_admin, public;

CREATE TABLE IF NOT EXISTS "user" (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name   nchar(100)  NOT NULL UNIQUE,
    first_name   nchar(100)  NOT NULL,
    last_name    nchar(100)  NOT NULL,
    email        nchar(250)  NOT NULL UNIQUE,
    phone_number nchar(25)   NOT NULL,
    company_name nchar(150)  NOT NULL DEFAULT '',
    role         integer     NOT NULL DEFAULT 0,
    is_active    boolean     NOT NULL DEFAULT true,
    session_lifetime_limit_days integer NOT NULL DEFAULT 1
);

ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS session_lifetime_limit_days integer NOT NULL DEFAULT 1;

UPDATE "user"
   SET session_lifetime_limit_days = 1
 WHERE session_lifetime_limit_days IS NULL
    OR session_lifetime_limit_days < 1;

ALTER TABLE "user"
    ALTER COLUMN session_lifetime_limit_days SET DEFAULT 1,
    ALTER COLUMN session_lifetime_limit_days SET NOT NULL;

CREATE TABLE IF NOT EXISTS session (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             integer      NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    login_name          nchar(100)   NOT NULL,
    client_machine_name  nchar(150)   NOT NULL DEFAULT '',
    login_time          timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_autorized        boolean      NOT NULL DEFAULT false
);

ALTER TABLE session
    DROP COLUMN IF EXISTS mac_address,
    ADD COLUMN IF NOT EXISTS login_time timestamp(6);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'iobeam_admin'
           AND table_name = 'session'
           AND column_name = 'last_signed_in'
    ) THEN
        EXECUTE 'UPDATE session
                    SET login_time = COALESCE(login_time, last_signed_in, CURRENT_TIMESTAMP)
                  WHERE login_time IS NULL';
    ELSE
        UPDATE session
           SET login_time = CURRENT_TIMESTAMP
         WHERE login_time IS NULL;
    END IF;
END;
$$;

ALTER TABLE session
    ALTER COLUMN login_time SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN login_time SET NOT NULL,
    DROP COLUMN IF EXISTS last_signed_in;

CREATE TABLE IF NOT EXISTS activity (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer      NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    activity_type   nchar(150)  NOT NULL,
    date            timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_signed_in  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    session_lifetime_limit_days integer NOT NULL DEFAULT 1
);

ALTER TABLE activity
    DROP COLUMN IF EXISTS data_file,
    DROP COLUMN IF EXISTS image_file,
    DROP COLUMN IF EXISTS data_file_name,
    DROP COLUMN IF EXISTS image_file_name,
    ADD COLUMN IF NOT EXISTS session_lifetime_limit_days integer NOT NULL DEFAULT 1,
    ALTER COLUMN last_signed_in SET DEFAULT CURRENT_TIMESTAMP;

UPDATE activity
   SET last_signed_in = CURRENT_TIMESTAMP
 WHERE last_signed_in IS NULL;

UPDATE activity
   SET session_lifetime_limit_days = 1
 WHERE session_lifetime_limit_days IS NULL
    OR session_lifetime_limit_days < 1;

ALTER TABLE activity
    ALTER COLUMN last_signed_in SET NOT NULL,
    ALTER COLUMN session_lifetime_limit_days SET DEFAULT 1,
    ALTER COLUMN session_lifetime_limit_days SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_session_user_login_time
    ON session (user_id, login_time DESC);

CREATE INDEX IF NOT EXISTS idx_activity_user_date
    ON activity (user_id, date DESC);

CREATE OR REPLACE PROCEDURE sp_user_insert(
    IN p_login_name nchar(100),
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    IN p_email nchar(250),
    IN p_phone_number nchar(25),
    IN p_company_name nchar(150),
    IN p_role integer,
    IN p_is_active boolean DEFAULT true,
    IN p_session_lifetime_limit_days integer DEFAULT 1,
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "user" (
        login_name, first_name, last_name, email,
        phone_number, company_name, role, is_active, session_lifetime_limit_days
    )
    VALUES (
        p_login_name, p_first_name, p_last_name, p_email,
        p_phone_number, COALESCE(p_company_name, ''), COALESCE(p_role, 0),
        COALESCE(p_is_active, true),
        GREATEST(1, COALESCE(p_session_lifetime_limit_days, 1))
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_update(
    IN p_id integer,
    IN p_login_name nchar(100),
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    IN p_email nchar(250),
    IN p_phone_number nchar(25),
    IN p_company_name nchar(150),
    IN p_role integer,
    IN p_is_active boolean,
    IN p_session_lifetime_limit_days integer DEFAULT 1
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "user"
       SET login_name = p_login_name,
           first_name = p_first_name,
           last_name = p_last_name,
           email = p_email,
           phone_number = p_phone_number,
           company_name = COALESCE(p_company_name, ''),
           role = COALESCE(p_role, 0),
           is_active = COALESCE(p_is_active, true),
           session_lifetime_limit_days = GREATEST(1, COALESCE(p_session_lifetime_limit_days, 1))
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM "user" WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_get_by_name(
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    INOUT p_result refcursor DEFAULT 'user_result'
)
LANGUAGE plpgsql
AS $$
BEGIN
    OPEN p_result FOR
        SELECT *
          FROM "user"
         WHERE first_name = p_first_name
           AND last_name = p_last_name;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_insert(
    IN p_user_id integer,
    IN p_login_name nchar(100),
    IN p_client_machine_name nchar(150),
    IN p_login_time timestamp(6),
    IN p_is_autorized boolean DEFAULT false,
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO session (
        user_id, login_name, client_machine_name, login_time, is_autorized
    )
    VALUES (
        p_user_id, p_login_name, COALESCE(p_client_machine_name, ''),
        COALESCE(p_login_time, CURRENT_TIMESTAMP), COALESCE(p_is_autorized, false)
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_update(
    IN p_id integer,
    IN p_user_id integer,
    IN p_login_name nchar(100),
    IN p_client_machine_name nchar(150),
    IN p_login_time timestamp(6),
    IN p_is_autorized boolean
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE session
       SET user_id = p_user_id,
           login_name = p_login_name,
           client_machine_name = COALESCE(p_client_machine_name, ''),
           login_time = COALESCE(p_login_time, CURRENT_TIMESTAMP),
           is_autorized = COALESCE(p_is_autorized, false)
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM session WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_insert(
    IN p_user_id integer,
    IN p_activity_type nchar(150),
    IN p_date timestamp(6),
    IN p_last_signed_in timestamp(6),
    IN p_session_lifetime_limit_days integer DEFAULT 1,
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO activity (
        user_id, activity_type, date, last_signed_in, session_lifetime_limit_days
    )
    VALUES (
        p_user_id, p_activity_type, COALESCE(p_date, CURRENT_TIMESTAMP),
        COALESCE(p_last_signed_in, CURRENT_TIMESTAMP),
        GREATEST(1, COALESCE(p_session_lifetime_limit_days, 1))
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_update(
    IN p_id integer,
    IN p_user_id integer,
    IN p_activity_type nchar(150),
    IN p_date timestamp(6),
    IN p_last_signed_in timestamp(6),
    IN p_session_lifetime_limit_days integer DEFAULT 1
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE activity
       SET user_id = p_user_id,
           activity_type = p_activity_type,
           date = COALESCE(p_date, CURRENT_TIMESTAMP),
           last_signed_in = COALESCE(p_last_signed_in, CURRENT_TIMESTAMP),
           session_lifetime_limit_days = GREATEST(1, COALESCE(p_session_lifetime_limit_days, 1))
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM activity WHERE id = p_id;
END;
$$;

CREATE OR REPLACE FUNCTION fn_activity_report(
    IN p_user_ids integer[],
    IN p_days integer DEFAULT 90
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
    WITH scoped_activity AS (
        SELECT
            a.id,
            a.user_id,
            btrim(u.login_name::text) AS login_name,
            btrim(u.first_name::text) AS first_name,
            btrim(u.last_name::text) AS last_name,
            btrim(a.activity_type::text) AS activity_type,
            a.date,
            CASE
                WHEN upper(btrim(a.activity_type::text)) LIKE '%RASTER%' THEN 'raster'
                WHEN upper(btrim(a.activity_type::text)) LIKE '%VECTOR%'
                  OR upper(btrim(a.activity_type::text)) LIKE '%VECTER%' THEN 'vector'
                ELSE 'other'
            END AS scan_kind,
            COALESCE(btrim(latest_session.client_machine_name::text), '') AS client_source
        FROM activity a
        JOIN "user" u ON u.id = a.user_id
        LEFT JOIN LATERAL (
            SELECT s.client_machine_name
              FROM session s
             WHERE s.user_id = a.user_id
             ORDER BY s.login_time DESC
             LIMIT 1
        ) latest_session ON true
        WHERE a.user_id = ANY(p_user_ids)
          AND a.date >= CURRENT_TIMESTAMP - (GREATEST(1, LEAST(365, COALESCE(p_days, 90))) * INTERVAL '1 day')
    ),
    normalized AS (
        SELECT
            *,
            CASE
                WHEN client_source = '' THEN 'Unknown'
                WHEN client_source IN ('127.0.0.1', '::1', '::ffff:127.0.0.1') THEN 'Localhost'
                WHEN client_source LIKE '10.%'
                  OR client_source LIKE '192.168.%'
                  OR client_source LIKE '172.16.%'
                  OR client_source LIKE '172.17.%'
                  OR client_source LIKE '172.18.%'
                  OR client_source LIKE '172.19.%'
                  OR client_source LIKE '172.2_.%'
                  OR client_source LIKE '172.30.%'
                  OR client_source LIKE '172.31.%' THEN 'Private network'
                ELSE client_source
            END AS location
        FROM scoped_activity
    )
    SELECT jsonb_build_object(
        'totals', COALESCE((
            SELECT jsonb_agg(row_to_json(t) ORDER BY t.total_scans DESC, t.login_name)
            FROM (
                SELECT
                    user_id,
                    login_name,
                    concat_ws(' ', nullif(first_name, ''), nullif(last_name, '')) AS name,
                    COUNT(*)::int AS total_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'raster')::int AS raster_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'vector')::int AS vector_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'other')::int AS other_activity,
                    MAX(date) AS last_activity
                FROM normalized
                GROUP BY user_id, login_name, first_name, last_name
            ) t
        ), '[]'::jsonb),
        'daily', COALESCE((
            SELECT jsonb_agg(row_to_json(d) ORDER BY d.bucket, d.login_name)
            FROM (
                SELECT
                    user_id,
                    login_name,
                    to_char(date_trunc('day', date), 'YYYY-MM-DD') AS bucket,
                    COUNT(*) FILTER (WHERE scan_kind = 'raster')::int AS raster_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'vector')::int AS vector_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'other')::int AS other_activity,
                    COUNT(*)::int AS total_scans
                FROM normalized
                GROUP BY user_id, login_name, date_trunc('day', date)
            ) d
        ), '[]'::jsonb),
        'weekly', COALESCE((
            SELECT jsonb_agg(row_to_json(w) ORDER BY w.week_start, w.login_name)
            FROM (
                SELECT
                    user_id,
                    login_name,
                    to_char(date_trunc('week', date), 'YYYY-MM-DD') AS week_start,
                    COUNT(*) FILTER (WHERE scan_kind = 'raster')::int AS raster_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'vector')::int AS vector_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'other')::int AS other_activity,
                    COUNT(*)::int AS total_scans
                FROM normalized
                GROUP BY user_id, login_name, date_trunc('week', date)
            ) w
        ), '[]'::jsonb),
        'geography', COALESCE((
            SELECT jsonb_agg(row_to_json(g) ORDER BY g.total_scans DESC, g.location)
            FROM (
                SELECT
                    location,
                    COUNT(DISTINCT user_id)::int AS accounts,
                    COUNT(*)::int AS total_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'raster')::int AS raster_scans,
                    COUNT(*) FILTER (WHERE scan_kind = 'vector')::int AS vector_scans,
                    MAX(date) AS last_activity
                FROM normalized
                GROUP BY location
            ) g
        ), '[]'::jsonb),
        'recent', COALESCE((
            SELECT jsonb_agg(row_to_json(r) ORDER BY r.date DESC)
            FROM (
                SELECT
                    user_id,
                    login_name,
                    activity_type,
                    scan_kind,
                    location,
                    date
                FROM normalized
                ORDER BY date DESC
                LIMIT 24
            ) r
        ), '[]'::jsonb)
    );
$$;
