CREATE SCHEMA IF NOT EXISTS iobeam_admin;
SET search_path TO iobeam_admin, public;

CREATE TABLE IF NOT EXISTS "user" (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name   nchar(100)  NOT NULL UNIQUE,
    first_name   nchar(100)  NOT NULL,
    last_name    nchar(100)  NOT NULL,
    email        nchar(250)  NOT NULL UNIQUE,
    phone_number nchar(25)   NOT NULL,
    company_name nchar(150)  NOT NULL DEFAULT '',
    role         integer     NOT NULL DEFAULT 0,
    is_active    boolean     NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS session (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             integer      NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    login_name          nchar(100)   NOT NULL,
    client_machine_name  nchar(150)   NOT NULL DEFAULT '',
    login_time          timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_autorized        boolean      NOT NULL DEFAULT false
);

ALTER TABLE session
    DROP COLUMN IF EXISTS mac_address,
    ADD COLUMN IF NOT EXISTS login_time timestamp(6);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM information_schema.columns
         WHERE table_schema = 'iobeam_admin'
           AND table_name = 'session'
           AND column_name = 'last_signed_in'
    ) THEN
        EXECUTE 'UPDATE session
                    SET login_time = COALESCE(login_time, last_signed_in, CURRENT_TIMESTAMP)
                  WHERE login_time IS NULL';
    ELSE
        UPDATE session
           SET login_time = CURRENT_TIMESTAMP
         WHERE login_time IS NULL;
    END IF;
END;
$$;

ALTER TABLE session
    ALTER COLUMN login_time SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN login_time SET NOT NULL,
    DROP COLUMN IF EXISTS last_signed_in;

CREATE TABLE IF NOT EXISTS activity (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer      NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    activity_type   nchar(150)  NOT NULL,
    date            timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_signed_in  timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE activity
    DROP COLUMN IF EXISTS data_file,
    DROP COLUMN IF EXISTS image_file,
    DROP COLUMN IF EXISTS data_file_name,
    DROP COLUMN IF EXISTS image_file_name,
    ALTER COLUMN last_signed_in SET DEFAULT CURRENT_TIMESTAMP;

UPDATE activity
   SET last_signed_in = CURRENT_TIMESTAMP
 WHERE last_signed_in IS NULL;

ALTER TABLE activity
    ALTER COLUMN last_signed_in SET NOT NULL;

CREATE OR REPLACE PROCEDURE sp_user_insert(
    IN p_login_name nchar(100),
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    IN p_email nchar(250),
    IN p_phone_number nchar(25),
    IN p_company_name nchar(150),
    IN p_role integer,
    IN p_is_active boolean DEFAULT true,
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO "user" (
        login_name, first_name, last_name, email,
        phone_number, company_name, role, is_active
    )
    VALUES (
        p_login_name, p_first_name, p_last_name, p_email,
        p_phone_number, COALESCE(p_company_name, ''), COALESCE(p_role, 0),
        COALESCE(p_is_active, true)
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_update(
    IN p_id integer,
    IN p_login_name nchar(100),
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    IN p_email nchar(250),
    IN p_phone_number nchar(25),
    IN p_company_name nchar(150),
    IN p_role integer,
    IN p_is_active boolean
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE "user"
       SET login_name = p_login_name,
           first_name = p_first_name,
           last_name = p_last_name,
           email = p_email,
           phone_number = p_phone_number,
           company_name = COALESCE(p_company_name, ''),
           role = COALESCE(p_role, 0),
           is_active = COALESCE(p_is_active, true)
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM "user" WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_user_get_by_name(
    IN p_first_name nchar(100),
    IN p_last_name nchar(100),
    INOUT p_result refcursor DEFAULT 'user_result'
)
LANGUAGE plpgsql
AS $$
BEGIN
    OPEN p_result FOR
        SELECT *
          FROM "user"
         WHERE first_name = p_first_name
           AND last_name = p_last_name;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_insert(
    IN p_user_id integer,
    IN p_login_name nchar(100),
    IN p_client_machine_name nchar(150),
    IN p_login_time timestamp(6),
    IN p_is_autorized boolean DEFAULT false,
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO session (
        user_id, login_name, client_machine_name, login_time, is_autorized
    )
    VALUES (
        p_user_id, p_login_name, COALESCE(p_client_machine_name, ''),
        COALESCE(p_login_time, CURRENT_TIMESTAMP), COALESCE(p_is_autorized, false)
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_update(
    IN p_id integer,
    IN p_user_id integer,
    IN p_login_name nchar(100),
    IN p_client_machine_name nchar(150),
    IN p_login_time timestamp(6),
    IN p_is_autorized boolean
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE session
       SET user_id = p_user_id,
           login_name = p_login_name,
           client_machine_name = COALESCE(p_client_machine_name, ''),
           login_time = COALESCE(p_login_time, CURRENT_TIMESTAMP),
           is_autorized = COALESCE(p_is_autorized, false)
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_session_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM session WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_insert(
    IN p_user_id integer,
    IN p_activity_type nchar(150),
    IN p_date timestamp(6),
    IN p_last_signed_in timestamp(6),
    INOUT p_id integer DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO activity (
        user_id, activity_type, date, last_signed_in
    )
    VALUES (
        p_user_id, p_activity_type, COALESCE(p_date, CURRENT_TIMESTAMP),
        COALESCE(p_last_signed_in, CURRENT_TIMESTAMP)
    )
    RETURNING id INTO p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_update(
    IN p_id integer,
    IN p_user_id integer,
    IN p_activity_type nchar(150),
    IN p_date timestamp(6),
    IN p_last_signed_in timestamp(6)
)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE activity
       SET user_id = p_user_id,
           activity_type = p_activity_type,
           date = COALESCE(p_date, CURRENT_TIMESTAMP),
           last_signed_in = COALESCE(p_last_signed_in, CURRENT_TIMESTAMP)
     WHERE id = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_activity_delete(
    IN p_id integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM activity WHERE id = p_id;
END;
$$;
