-- =====================================================================================================
-- 003_calibration_schema.sql  -  FIB | SEM equipment calibration-parameter management
--
-- Loaded after 001_schema.sql (and 002 when seeding) by applyAdminDatabaseSetup(); fully idempotent, like
-- 001. Objects live in the existing `ionbeam_asset` schema, next to ionbeam_asset.equipment, so a profile
-- is a real foreign-key child of a registered machine (DB235, FIB200, ...).
--
--   calibration_group / calibration_table   navigation tree and matrix / list layouts
--   calibration_parameter_definition        the catalog: one row per parameter (or one cell of a table)
--   calibration_profile                     (equipment, FIB|SEM) -> named profile with a revision counter
--   calibration_value                       current value of each parameter in a profile
--   calibration_revision                    append-only history: what changed + full snapshot per revision
--   calibration_definition_change           audit of catalog edits (e.g. naming a vendor-undocumented slot)
--
-- The catalog is loaded by 004_calibration_seed.sql (generated) via fn_seed_calibration_catalog().
-- Vendor credentials found in the machine-data files (IONI_PSWD1-4, usr\*\LOGIN\KEY) are NEVER catalogued.
--
-- Public functions (all take / return jsonb, called by ionbeam-web/backend/src/calibrationRepository.ts):
--   fn_list_calibration_groups            fn_get_equipment_calibration           fn_get_calibration_table
--   fn_upsert_equipment_calibration       fn_list_equipment_calibration_history
--   fn_restore_equipment_calibration_revision   fn_import_equipment_calibration
--   fn_update_calibration_definition      fn_seed_calibration_catalog
-- =====================================================================================================
CREATE SCHEMA IF NOT EXISTS iobeam_admin;
CREATE SCHEMA IF NOT EXISTS ionbeam_asset;
SET search_path TO ionbeam_asset, iobeam_admin, public;

-- ------------------------------------------------------------------------------------- navigation
CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_group (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type varchar(3)   NOT NULL CHECK (equipment_type IN ('FIB', 'SEM')),
    group_code     varchar(60)  NOT NULL,
    parent_code    varchar(60),
    label          varchar(200) NOT NULL,
    sort_order     integer      NOT NULL DEFAULT 0,
    UNIQUE (equipment_type, group_code)
);

CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_table (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type varchar(3)   NOT NULL CHECK (equipment_type IN ('FIB', 'SEM')),
    table_code     varchar(60)  NOT NULL,
    group_code     varchar(60)  NOT NULL,
    label          varchar(200) NOT NULL,
    kind           varchar(10)  NOT NULL CHECK (kind IN ('matrix', 'list')),
    row_header     varchar(100),
    col_header     varchar(100),
    note           text,
    layout         jsonb        NOT NULL DEFAULT '{"rows":[],"cols":[]}'::jsonb,   -- {rows:[{key,label,role}], cols:[{key,label,unit}]}
    UNIQUE (equipment_type, table_code),
    FOREIGN KEY (equipment_type, group_code) REFERENCES ionbeam_asset.calibration_group (equipment_type, group_code)
);

-- ------------------------------------------------------------------------------------- catalog
CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_parameter_definition (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_type  varchar(3)    NOT NULL CHECK (equipment_type IN ('FIB', 'SEM')),
    parameter_key   varchar(200)  NOT NULL,
    group_code      varchar(60)   NOT NULL,
    vendor_name     varchar(200),                               -- vendor symbol as written; NULL = vendor gave none
    display_name    varchar(300)  NOT NULL,
    description     text          NOT NULL DEFAULT '',
    value_type      varchar(10)   NOT NULL CHECK (value_type IN ('number', 'integer', 'boolean', 'text', 'enum')),
    unit            varchar(30)   NOT NULL DEFAULT '',
    unit_source     varchar(10)   CHECK (unit_source IN ('vendor', 'name', 'inferred')),
    minimum_value   double precision,                           -- static bounds
    maximum_value   double precision,
    limit_min_key   varchar(200),                               -- bounds held in other parameters of the same profile
    limit_max_key   varchar(200),
    default_value   jsonb,                                      -- vendor factory value where the vendor supplied one
    enum_options    jsonb,                                      -- [{"value":3,"label":"FIB600"}, ...]
    param_class     varchar(15)   NOT NULL CHECK (param_class IN
                        ('identity', 'config', 'calibration', 'tuning', 'limit', 'preset', 'counter', 'unused', 'undocumented')),
    access_level    varchar(10)   NOT NULL CHECK (access_level IN ('fixed', 'auto', 'service', 'adjustable')),
    is_read_only    boolean       NOT NULL DEFAULT false,
    shared_hardware boolean       NOT NULL DEFAULT false,       -- one physical device serves both FIB and SEM (stage, pumps)
    applicability   text[]        NOT NULL DEFAULT '{}',
    ui_widget       varchar(10)   NOT NULL DEFAULT 'number' CHECK (ui_widget IN ('number', 'toggle', 'select', 'readonly', 'raw', 'text')),
    adjustment_no   varchar(10),
    table_code      varchar(60),                                -- set => this definition is one cell of a table
    row_key         varchar(60),
    col_key         varchar(60),
    source_vendor   varchar(100)  NOT NULL DEFAULT '',
    source_document varchar(200)  NOT NULL DEFAULT '',
    source_url      varchar(500)  NOT NULL DEFAULT '',
    source_reference varchar(500) NOT NULL DEFAULT '',
    source_kind     varchar(5)    CHECK (source_kind IN ('int', 'float', 'reg')),
    source_slot     integer,
    source_path     varchar(500),                               -- registry leaf path (import matching key)
    source_line     integer,
    vendor_flags    varchar(60),
    semantics_known boolean       NOT NULL DEFAULT true,        -- false = the vendor never documented the meaning
    assign_basis    varchar(15)   CHECK (assign_basis IN ('vendor_file', 'registry_path', 'name_rule', 'default', 'manual')),
    assign_conf     varchar(6)    CHECK (assign_conf IN ('high', 'medium', 'low')),
    review_state    varchar(10)   NOT NULL DEFAULT 'imported' CHECK (review_state IN ('imported', 'reviewed', 'confirmed')),
    is_active       boolean       NOT NULL DEFAULT true,
    sort_order      integer       NOT NULL DEFAULT 0,
    update_date     timestamp(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (equipment_type, parameter_key),
    FOREIGN KEY (equipment_type, group_code) REFERENCES ionbeam_asset.calibration_group (equipment_type, group_code),
    FOREIGN KEY (equipment_type, table_code) REFERENCES ionbeam_asset.calibration_table (equipment_type, table_code),
    CONSTRAINT calibration_cell_all_or_none
        CHECK ((table_code IS NULL) = (row_key IS NULL) AND (table_code IS NULL) = (col_key IS NULL)),
    CONSTRAINT calibration_enum_needs_options CHECK (value_type <> 'enum' OR enum_options IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_calibration_def_cell
    ON ionbeam_asset.calibration_parameter_definition (equipment_type, table_code, row_key, col_key) WHERE table_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calibration_def_group
    ON ionbeam_asset.calibration_parameter_definition (equipment_type, group_code, sort_order);
CREATE INDEX IF NOT EXISTS idx_calibration_def_slot
    ON ionbeam_asset.calibration_parameter_definition (equipment_type, source_kind, source_slot) WHERE source_slot IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calibration_def_path
    ON ionbeam_asset.calibration_parameter_definition (equipment_type, source_path) WHERE source_path IS NOT NULL;

-- ------------------------------------------------------------------------------------- profiles & values
CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_profile (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id   integer      NOT NULL REFERENCES ionbeam_asset.equipment (id) ON DELETE CASCADE,
    equipment_type varchar(3)   NOT NULL CHECK (equipment_type IN ('FIB', 'SEM')),
    profile_name   varchar(100) NOT NULL DEFAULT 'default',
    revision       integer      NOT NULL DEFAULT 0,
    notes          text         NOT NULL DEFAULT '',
    is_active      boolean      NOT NULL DEFAULT true,
    updated_at     timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by     integer      REFERENCES iobeam_admin."user" (id) ON DELETE SET NULL,
    UNIQUE (equipment_id, equipment_type, profile_name)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_calibration_profile_active
    ON ionbeam_asset.calibration_profile (equipment_id, equipment_type) WHERE is_active;

CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_value (
    profile_id    integer NOT NULL REFERENCES ionbeam_asset.calibration_profile (id) ON DELETE CASCADE,
    definition_id integer NOT NULL REFERENCES ionbeam_asset.calibration_parameter_definition (id) ON DELETE RESTRICT,
    value_num     double precision,
    value_text    text,
    notes         text         NOT NULL DEFAULT '',
    verified_at   timestamp(6),
    update_date   timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (profile_id, definition_id),
    CHECK (value_num IS NULL OR value_text IS NULL)
);
CREATE INDEX IF NOT EXISTS idx_calibration_value_def ON ionbeam_asset.calibration_value (definition_id);

CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_revision (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    integer      NOT NULL REFERENCES ionbeam_asset.calibration_profile (id) ON DELETE CASCADE,
    revision      integer      NOT NULL,
    kind          varchar(10)  NOT NULL CHECK (kind IN ('edit', 'import', 'restore')),
    reason        text         NOT NULL DEFAULT '',
    source_ref    varchar(300) NOT NULL DEFAULT '',          -- file name for imports, 'revision N' for restores
    changes       jsonb        NOT NULL DEFAULT '[]'::jsonb, -- [{parameter_key, old, new}]
    changed_count integer      NOT NULL DEFAULT 0,
    full_snapshot jsonb        NOT NULL DEFAULT '{}'::jsonb, -- every value of the profile after this revision
    created_at    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    integer      REFERENCES iobeam_admin."user" (id) ON DELETE SET NULL,
    UNIQUE (profile_id, revision)
);

CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_revision_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'calibration_revision is append-only' USING ERRCODE = '55000';
END;
$$;
DROP TRIGGER IF EXISTS trg_calibration_revision_immutable ON ionbeam_asset.calibration_revision;
CREATE TRIGGER trg_calibration_revision_immutable
BEFORE UPDATE ON ionbeam_asset.calibration_revision
FOR EACH ROW EXECUTE FUNCTION ionbeam_asset.fn_calibration_revision_immutable();

CREATE TABLE IF NOT EXISTS ionbeam_asset.calibration_definition_change (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_id integer      NOT NULL REFERENCES ionbeam_asset.calibration_parameter_definition (id) ON DELETE CASCADE,
    changed_by    integer      REFERENCES iobeam_admin."user" (id) ON DELETE SET NULL,
    changed_at    timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    before_value  jsonb        NOT NULL,
    after_value   jsonb        NOT NULL
);

CREATE OR REPLACE FUNCTION ionbeam_asset.fn_touch_calibration_definition()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.update_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_calibration_definition_update_date ON ionbeam_asset.calibration_parameter_definition;
CREATE TRIGGER trg_calibration_definition_update_date
BEFORE UPDATE ON ionbeam_asset.calibration_parameter_definition
FOR EACH ROW EXECUTE FUNCTION ionbeam_asset.fn_touch_calibration_definition();

-- =====================================================================================================
-- helpers
-- =====================================================================================================
-- stored (num, text) -> JSON value typed by the definition
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_value_json(p_type text, p_num double precision, p_text text)
RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE
        WHEN p_type = 'text'                 THEN CASE WHEN p_text IS NULL THEN NULL ELSE to_jsonb(p_text) END
        WHEN p_num IS NULL                   THEN NULL
        WHEN p_type = 'boolean'              THEN to_jsonb(p_num <> 0)
        WHEN p_type IN ('integer', 'enum')   THEN to_jsonb(round(p_num)::bigint)
        ELSE to_jsonb(p_num)
    END;
$$;

-- request payload value -> {ok, num, text} | {ok:false, message}
-- p_strict_enum: an edit must pick a documented enum value; imports and restores accept what the machine holds
-- (the vendor's comments are not always exhaustive, e.g. IONI_DET_USED is documented 0=E 1=I but is 2 on the supplied machine).
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_coerce(
    d ionbeam_asset.calibration_parameter_definition, v jsonb, p_strict_enum boolean DEFAULT true)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    n double precision;
    s text;
BEGIN
    IF d.value_type = 'text' THEN
        IF v IS NULL OR jsonb_typeof(v) = 'null' THEN
            RETURN jsonb_build_object('ok', true, 'num', NULL, 'text', NULL);
        END IF;
        IF jsonb_typeof(v) <> 'string' THEN
            RETURN jsonb_build_object('ok', false, 'message', 'text value expected');
        END IF;
        RETURN jsonb_build_object('ok', true, 'num', NULL, 'text', v #>> '{}');
    END IF;
    IF v IS NULL OR jsonb_typeof(v) = 'null' OR (jsonb_typeof(v) = 'string' AND btrim(v #>> '{}') = '') THEN
        RETURN jsonb_build_object('ok', false, 'message', 'a value is required');
    END IF;
    IF d.value_type = 'boolean' THEN
        IF jsonb_typeof(v) = 'boolean' THEN
            n := CASE WHEN (v #>> '{}')::boolean THEN 1 ELSE 0 END;
        ELSIF jsonb_typeof(v) = 'number' AND (v #>> '{}')::numeric IN (0, 1) THEN
            n := (v #>> '{}')::numeric;
        ELSIF jsonb_typeof(v) = 'string' AND lower(btrim(v #>> '{}')) IN ('true', '1', 'yes', 'on') THEN
            n := 1;
        ELSIF jsonb_typeof(v) = 'string' AND lower(btrim(v #>> '{}')) IN ('false', '0', 'no', 'off') THEN
            n := 0;
        ELSE
            RETURN jsonb_build_object('ok', false, 'message', 'boolean expected (true/false)');
        END IF;
        RETURN jsonb_build_object('ok', true, 'num', n, 'text', NULL);
    END IF;
    s := btrim(v #>> '{}');
    IF jsonb_typeof(v) NOT IN ('number', 'string') OR s !~ '^[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?$' THEN
        RETURN jsonb_build_object('ok', false, 'message', 'number expected');
    END IF;
    n := s::double precision;
    IF d.value_type IN ('integer', 'enum') AND n <> round(n) THEN
        RETURN jsonb_build_object('ok', false, 'message', 'integer expected');
    END IF;
    IF d.value_type = 'enum' AND p_strict_enum AND NOT EXISTS (
        SELECT 1 FROM jsonb_array_elements(d.enum_options) o WHERE (o ->> 'value')::numeric = n::numeric
    ) THEN
        RETURN jsonb_build_object('ok', false, 'message',
            'must be one of: ' || (SELECT string_agg((o ->> 'value') || ' (' || (o ->> 'label') || ')', ', ')
                                     FROM jsonb_array_elements(d.enum_options) o));
    END IF;
    RETURN jsonb_build_object('ok', true, 'num', n, 'text', NULL);
END;
$$;

CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_find_profile(
    p_equipment_id integer, p_type text, p_name text DEFAULT NULL)
RETURNS integer LANGUAGE sql STABLE AS $$
    SELECT id FROM ionbeam_asset.calibration_profile
     WHERE equipment_id = p_equipment_id AND equipment_type = p_type
       AND ((p_name IS NOT NULL AND btrim(p_name) <> '' AND profile_name = btrim(p_name))
         OR ((p_name IS NULL OR btrim(p_name) = '') AND is_active))
     ORDER BY is_active DESC, id LIMIT 1;
$$;

-- minimum role (iobeam_admin.user.role: 0 user, 1 super user, 2 developer, 3 admin) that may write a parameter
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_required_role(p_access text)
RETURNS integer LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE p_access WHEN 'adjustable' THEN 1 WHEN 'fixed' THEN 3 ELSE 2 END;
$$;

CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_needs_ack(d ionbeam_asset.calibration_parameter_definition)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
    SELECT CASE
        WHEN NOT d.semantics_known OR d.param_class = 'undocumented' THEN 'the vendor did not document what this slot does'
        WHEN d.access_level = 'fixed'                                 THEN 'the vendor marks this value as fixed'
        WHEN d.assign_conf = 'low'                                    THEN 'the classification of this parameter is low-confidence'
        ELSE NULL END;
$$;

-- one definition as JSON (the shape of CalibrationParameterDefinition in calibrationRepository.ts + extensions)
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_definition_json(
    d ionbeam_asset.calibration_parameter_definition, p_category text,
    p_dyn_min double precision DEFAULT NULL, p_dyn_max double precision DEFAULT NULL)
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object(
        'id', d.id, 'equipment_type', d.equipment_type, 'parameter_key', d.parameter_key,
        'category', p_category, 'display_name', d.display_name, 'description', d.description,
        'value_type', d.value_type, 'unit', d.unit,
        'minimum_value', COALESCE(d.minimum_value, p_dyn_min), 'maximum_value', COALESCE(d.maximum_value, p_dyn_max),
        'default_value', d.default_value,
        'enum_values', COALESCE((SELECT jsonb_agg(o ->> 'label') FROM jsonb_array_elements(d.enum_options) o), '[]'::jsonb),
        'source_vendor', d.source_vendor, 'source_document', d.source_document, 'source_url', d.source_url,
        'source_reference', d.source_reference, 'is_read_only', d.is_read_only, 'sort_order', d.sort_order
    ) || jsonb_build_object(
        'group_code', d.group_code, 'vendor_name', d.vendor_name, 'param_class', d.param_class,
        'access_level', d.access_level, 'ui_widget', d.ui_widget,
        'enum_options', COALESCE(d.enum_options, '[]'::jsonb), 'unit_source', d.unit_source,
        'table_code', d.table_code, 'row_key', d.row_key, 'col_key', d.col_key,
        'semantics_known', d.semantics_known, 'assign_basis', d.assign_basis, 'assign_conf', d.assign_conf,
        'review_state', d.review_state, 'applicability', to_jsonb(d.applicability),
        'shared_hardware', d.shared_hardware, 'adjustment_no', d.adjustment_no,
        'limit_min_key', d.limit_min_key, 'limit_max_key', d.limit_max_key
    );
$$;

-- profile row -> JSON
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_profile_json(p ionbeam_asset.calibration_profile)
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT jsonb_build_object('id', p.id, 'equipment_id', p.equipment_id, 'equipment_type', p.equipment_type,
                              'profile_name', p.profile_name, 'revision', p.revision, 'notes', p.notes,
                              'is_active', p.is_active, 'updated_at', p.updated_at, 'updated_by', p.updated_by);
$$;

-- every stored value of a profile as {parameter_key: json}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_snapshot(p_profile_id integer)
RETURNS jsonb LANGUAGE sql STABLE AS $$
    SELECT COALESCE(jsonb_object_agg(d.parameter_key, ionbeam_asset.fn_calibration_value_json(d.value_type, v.value_num, v.value_text)), '{}'::jsonb)
      FROM ionbeam_asset.calibration_value v
      JOIN ionbeam_asset.calibration_parameter_definition d ON d.id = v.definition_id
     WHERE v.profile_id = p_profile_id AND (v.value_num IS NOT NULL OR v.value_text IS NOT NULL);
$$;

-- =====================================================================================================
-- write path: validate -> (optionally) apply. Used by upsert, restore and import.
-- =====================================================================================================
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_calibration_apply(
    p_profile_id        integer,
    p_items             jsonb,            -- [{parameter_key, value, notes?, verified?}]
    p_kind              text,             -- edit | import | restore
    p_reason            text,
    p_actor             integer,
    p_actor_role        integer,
    p_ack               boolean,
    p_expected_revision integer,
    p_source_ref        text,
    p_enforce           boolean,          -- role + risk-acknowledgement checks
    p_check_limits      boolean,
    p_dry_run           boolean)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
    prof        ionbeam_asset.calibration_profile%ROWTYPE;
    it          jsonb;
    d           ionbeam_asset.calibration_parameter_definition%ROWTYPE;
    c           jsonb;
    cur         ionbeam_asset.calibration_value%ROWTYPE;
    key         text;
    errors      jsonb := '[]'::jsonb;
    warnings    jsonb := '[]'::jsonb;
    changes     jsonb := '[]'::jsonb;
    newvals     jsonb := '{}'::jsonb;           -- key -> numeric value proposed in this request (for limit checks)
    proposed    jsonb := '[]'::jsonb;           -- [{def_id, key, num, text, notes, verified, old, new, changed}]
    ack_needed  jsonb := '[]'::jsonb;
    ack_reason  text;
    lo double precision; hi double precision;
    lim double precision;
    prop        jsonb;
    unchanged   integer := 0;
    annotated   integer := 0;
    n_changed   integer := 0;
    new_rev     integer;
    snap        jsonb;
    seen        text[] := ARRAY[]::text[];
BEGIN
    SELECT * INTO prof FROM ionbeam_asset.calibration_profile WHERE id = p_profile_id FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'profile not found');
    END IF;
    IF p_expected_revision IS NOT NULL AND p_expected_revision <> prof.revision THEN
        RETURN jsonb_build_object('ok', false, 'error', 'revision_conflict',
            'message', format('the profile is at revision %s but you edited revision %s - reload and retry', prof.revision, p_expected_revision),
            'current_revision', prof.revision);
    END IF;

    -- pass 1: resolve, coerce, role / acknowledgement --------------------------------------------------
    FOR it IN SELECT value FROM jsonb_array_elements(COALESCE(p_items, '[]'::jsonb))
    LOOP
        key := btrim(COALESCE(it ->> 'parameter_key', ''));
        SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition
         WHERE equipment_type = prof.equipment_type AND parameter_key = key AND is_active;
        IF NOT FOUND THEN
            errors := errors || jsonb_build_object('parameter_key', key, 'code', 'unknown_parameter',
                        'message', format('%s has no parameter "%s"', prof.equipment_type, key));
            CONTINUE;
        END IF;
        IF key = ANY (seen) THEN
            errors := errors || jsonb_build_object('parameter_key', key, 'code', 'duplicate', 'message', 'parameter listed twice');
            CONTINUE;
        END IF;
        seen := array_append(seen, key);

        IF COALESCE((it ->> 'clear')::boolean, false) THEN
            c := jsonb_build_object('ok', true, 'num', NULL, 'text', NULL);       -- remove the stored value
        ELSE
            c := ionbeam_asset.fn_calibration_coerce(d, it -> 'value', p_kind = 'edit');
            IF NOT (c ->> 'ok')::boolean THEN
                errors := errors || jsonb_build_object('parameter_key', key, 'code', 'invalid_value', 'message', c ->> 'message');
                CONTINUE;
            END IF;
        END IF;

        SELECT * INTO cur FROM ionbeam_asset.calibration_value WHERE profile_id = p_profile_id AND definition_id = d.id;
        prop := jsonb_build_object(
            'def_id', d.id, 'key', key, 'num', c -> 'num', 'text', c -> 'text',
            'notes', it -> 'notes', 'verified', COALESCE((it ->> 'verified')::boolean, false),
            'old', CASE WHEN FOUND THEN ionbeam_asset.fn_calibration_value_json(d.value_type, cur.value_num, cur.value_text) END,
            'new', ionbeam_asset.fn_calibration_value_json(d.value_type, (c ->> 'num')::double precision, c ->> 'text'),
            'changed', (NOT FOUND) OR cur.value_num IS DISTINCT FROM (c ->> 'num')::double precision
                                    OR cur.value_text IS DISTINCT FROM (c ->> 'text'),
            'has_row', FOUND,
            'clear', COALESCE((it ->> 'clear')::boolean, false));
        IF (prop ->> 'changed')::boolean AND jsonb_typeof(prop -> 'new') = 'null' AND jsonb_typeof(prop -> 'old') = 'null' THEN
            prop := jsonb_set(prop, '{changed}', 'false');      -- NULL -> NULL is not a change
        END IF;

        IF p_enforce AND (prop ->> 'changed')::boolean THEN
            IF p_actor_role < ionbeam_asset.fn_calibration_required_role(d.access_level) THEN
                errors := errors || jsonb_build_object('parameter_key', key, 'code', 'forbidden_role',
                    'message', format('%s parameters need role %s or higher', d.access_level, ionbeam_asset.fn_calibration_required_role(d.access_level)));
                CONTINUE;
            END IF;
            ack_reason := ionbeam_asset.fn_calibration_needs_ack(d);
            IF ack_reason IS NOT NULL AND NOT COALESCE(p_ack, false) THEN
                ack_needed := ack_needed || jsonb_build_object('parameter_key', key, 'code', 'risk_ack_required', 'message', ack_reason);
            END IF;
        END IF;
        IF (c ->> 'num') IS NOT NULL THEN
            newvals := newvals || jsonb_build_object(key, (c -> 'num'));
        END IF;
        proposed := proposed || prop;
    END LOOP;

    -- pass 2: limits (static bounds, then bounds held in other parameters) -------------------------------
    IF p_check_limits THEN
        FOR prop IN SELECT value FROM jsonb_array_elements(proposed)
        LOOP
            CONTINUE WHEN NOT (prop ->> 'changed')::boolean OR (prop -> 'num') IS NULL OR jsonb_typeof(prop -> 'num') = 'null';
            SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition WHERE id = (prop ->> 'def_id')::integer;
            lo := d.minimum_value;  hi := d.maximum_value;
            IF lo IS NULL AND d.limit_min_key IS NOT NULL THEN
                lo := COALESCE((newvals ->> d.limit_min_key)::double precision,
                               (SELECT v.value_num FROM ionbeam_asset.calibration_value v
                                  JOIN ionbeam_asset.calibration_parameter_definition x ON x.id = v.definition_id
                                 WHERE v.profile_id = p_profile_id AND x.equipment_type = prof.equipment_type AND x.parameter_key = d.limit_min_key));
            END IF;
            IF hi IS NULL AND d.limit_max_key IS NOT NULL THEN
                hi := COALESCE((newvals ->> d.limit_max_key)::double precision,
                               (SELECT v.value_num FROM ionbeam_asset.calibration_value v
                                  JOIN ionbeam_asset.calibration_parameter_definition x ON x.id = v.definition_id
                                 WHERE v.profile_id = p_profile_id AND x.equipment_type = prof.equipment_type AND x.parameter_key = d.limit_max_key));
            END IF;
            lim := (prop ->> 'num')::double precision;
            -- an unset / inverted pair (0/0, min>max) means "no limit" in the vendor files
            IF lo IS NOT NULL AND hi IS NOT NULL AND lo <= hi AND NOT (lo = 0 AND hi = 0) AND (lim < lo OR lim > hi) THEN
                errors := errors || jsonb_build_object('parameter_key', d.parameter_key, 'code', 'out_of_range',
                            'message', format('outside the vendor limits [%s .. %s]', lo, hi));
            END IF;
        END LOOP;
    END IF;

    IF jsonb_array_length(errors) > 0 OR jsonb_array_length(ack_needed) > 0 THEN
        RETURN jsonb_build_object('ok', false,
            'error', CASE WHEN jsonb_array_length(errors) > 0 THEN 'validation_failed' ELSE 'risk_ack_required' END,
            'errors', errors || ack_needed);
    END IF;

    -- summarise ----------------------------------------------------------------------------------------
    FOR prop IN SELECT value FROM jsonb_array_elements(proposed)
    LOOP
        IF (prop ->> 'changed')::boolean THEN
            n_changed := n_changed + 1;
            changes := changes || jsonb_build_object('parameter_key', prop ->> 'key', 'old', prop -> 'old', 'new', prop -> 'new');
        ELSE
            unchanged := unchanged + 1;
        END IF;
    END LOOP;

    IF p_dry_run THEN
        RETURN jsonb_build_object('ok', true, 'dry_run', true, 'revision', prof.revision, 'changed', n_changed,
                                  'unchanged', unchanged, 'changes', changes);
    END IF;

    -- write --------------------------------------------------------------------------------------------
    FOR prop IN SELECT value FROM jsonb_array_elements(proposed)
    LOOP
        IF (prop ->> 'changed')::boolean AND (prop ->> 'clear')::boolean THEN
            DELETE FROM ionbeam_asset.calibration_value
             WHERE profile_id = p_profile_id AND definition_id = (prop ->> 'def_id')::integer;
        ELSIF (prop ->> 'changed')::boolean THEN
            INSERT INTO ionbeam_asset.calibration_value AS v (profile_id, definition_id, value_num, value_text, notes, verified_at, update_date)
            VALUES (p_profile_id, (prop ->> 'def_id')::integer,
                    (prop ->> 'num')::double precision, prop ->> 'text',
                    COALESCE(prop ->> 'notes', ''), CASE WHEN (prop ->> 'verified')::boolean THEN CURRENT_TIMESTAMP END, CURRENT_TIMESTAMP)
            ON CONFLICT (profile_id, definition_id) DO UPDATE
               SET value_num = EXCLUDED.value_num, value_text = EXCLUDED.value_text,
                   notes = COALESCE(prop ->> 'notes', v.notes),
                   verified_at = CASE WHEN (prop ->> 'verified')::boolean THEN CURRENT_TIMESTAMP ELSE v.verified_at END,
                   update_date = CURRENT_TIMESTAMP;
        ELSIF (prop ->> 'has_row')::boolean AND ((prop ->> 'notes') IS NOT NULL OR (prop ->> 'verified')::boolean) THEN
            UPDATE ionbeam_asset.calibration_value
               SET notes = COALESCE(prop ->> 'notes', notes),
                   verified_at = CASE WHEN (prop ->> 'verified')::boolean THEN CURRENT_TIMESTAMP ELSE verified_at END,
                   update_date = CURRENT_TIMESTAMP
             WHERE profile_id = p_profile_id AND definition_id = (prop ->> 'def_id')::integer;
            annotated := annotated + 1;
        END IF;
    END LOOP;

    new_rev := prof.revision;
    IF n_changed > 0 THEN
        new_rev := prof.revision + 1;
        snap := ionbeam_asset.fn_calibration_snapshot(p_profile_id);
        INSERT INTO ionbeam_asset.calibration_revision (profile_id, revision, kind, reason, source_ref, changes, changed_count, full_snapshot, created_by)
        VALUES (p_profile_id, new_rev, p_kind, COALESCE(p_reason, ''), COALESCE(p_source_ref, ''), changes, n_changed, snap, p_actor);
        UPDATE ionbeam_asset.calibration_profile
           SET revision = new_rev, updated_at = CURRENT_TIMESTAMP, updated_by = p_actor
         WHERE id = p_profile_id;
    END IF;

    RETURN jsonb_build_object('ok', true, 'revision', new_rev, 'changed', n_changed, 'unchanged', unchanged,
                              'annotated', annotated, 'changes', changes, 'warnings', warnings);
END;
$$;

-- =====================================================================================================
-- read path
-- =====================================================================================================
-- Navigation tree with counts.  payload: {equipment_type, equipment_id?, profile_name?}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_list_calibration_groups(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    et   text := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    eq   integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    pid  integer;
    out  jsonb;
BEGIN
    IF et NOT IN ('FIB', 'SEM') THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment_type must be FIB or SEM');
    END IF;
    IF eq IS NOT NULL THEN
        pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    END IF;
    WITH cnt AS (
        SELECT d.group_code,
               count(*) FILTER (WHERE d.table_code IS NULL)                                        AS parameters,
               count(*) FILTER (WHERE d.table_code IS NOT NULL)                                    AS table_cells,
               count(*) FILTER (WHERE NOT d.semantics_known OR d.param_class = 'undocumented')     AS undocumented,
               count(*) FILTER (WHERE d.assign_conf = 'low')                                       AS low_confidence,
               count(*) FILTER (WHERE d.review_state = 'imported')                                 AS unreviewed,
               count(v.definition_id)                                                              AS with_values
          FROM ionbeam_asset.calibration_parameter_definition d
          LEFT JOIN ionbeam_asset.calibration_value v ON v.profile_id = pid AND v.definition_id = d.id
         WHERE d.equipment_type = et AND d.is_active
         GROUP BY d.group_code
    )
    SELECT jsonb_build_object(
        'ok', true, 'equipment_type', et,
        'groups', COALESCE(jsonb_agg(jsonb_build_object(
            'group_code', g.group_code, 'parent_code', g.parent_code, 'label', g.label, 'sort_order', g.sort_order,
            'parameters',     COALESCE(c.parameters, 0),     'table_cells',   COALESCE(c.table_cells, 0),
            'undocumented',   COALESCE(c.undocumented, 0),   'low_confidence', COALESCE(c.low_confidence, 0),
            'unreviewed',     COALESCE(c.unreviewed, 0),     'with_values',   COALESCE(c.with_values, 0),
            'total_parameters',   (SELECT COALESCE(sum(x.parameters), 0)     FROM cnt x WHERE x.group_code = g.group_code OR x.group_code LIKE g.group_code || '.%'),
            'total_table_cells',  (SELECT COALESCE(sum(x.table_cells), 0)    FROM cnt x WHERE x.group_code = g.group_code OR x.group_code LIKE g.group_code || '.%'),
            'total_undocumented', (SELECT COALESCE(sum(x.undocumented), 0)   FROM cnt x WHERE x.group_code = g.group_code OR x.group_code LIKE g.group_code || '.%'),
            'total_low_confidence', (SELECT COALESCE(sum(x.low_confidence), 0) FROM cnt x WHERE x.group_code = g.group_code OR x.group_code LIKE g.group_code || '.%'),
            'total_with_values',  (SELECT COALESCE(sum(x.with_values), 0)    FROM cnt x WHERE x.group_code = g.group_code OR x.group_code LIKE g.group_code || '.%'),
            'tables', COALESCE((SELECT jsonb_agg(jsonb_build_object('table_code', t.table_code, 'label', t.label, 'kind', t.kind) ORDER BY t.id)
                                  FROM ionbeam_asset.calibration_table t
                                 WHERE t.equipment_type = g.equipment_type AND t.group_code = g.group_code), '[]'::jsonb)
        ) ORDER BY g.sort_order), '[]'::jsonb),
        'quality', jsonb_build_object(
            'definitions',    (SELECT COALESCE(sum(parameters + table_cells), 0) FROM cnt),
            'undocumented',   (SELECT COALESCE(sum(undocumented), 0) FROM cnt),
            'low_confidence', (SELECT COALESCE(sum(low_confidence), 0) FROM cnt),
            'unreviewed',     (SELECT COALESCE(sum(unreviewed), 0) FROM cnt),
            'with_values',    (SELECT COALESCE(sum(with_values), 0) FROM cnt))
    ) INTO out
      FROM ionbeam_asset.calibration_group g LEFT JOIN cnt c ON c.group_code = g.group_code
     WHERE g.equipment_type = et;
    RETURN out;
END;
$$;

-- Definitions + stored values for one equipment/type.
-- payload: {equipment_id, equipment_type, profile_name?, group_code?, q?, param_class?, access_level?, undocumented?,
--           low_confidence?, review_state?, include_cells?, keys?, limit?, offset?}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_get_equipment_calibration(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    eq        integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et        text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    pid       integer;
    prof      ionbeam_asset.calibration_profile%ROWTYPE;
    f_group   text    := NULLIF(btrim(COALESCE(p_payload ->> 'group_code', '')), '');
    f_q       text    := NULLIF(lower(btrim(COALESCE(p_payload ->> 'q', ''))), '');
    f_class   text    := NULLIF(p_payload ->> 'param_class', '');
    f_access  text    := NULLIF(p_payload ->> 'access_level', '');
    f_undoc   boolean := (p_payload ->> 'undocumented')::boolean;
    f_low     boolean := (p_payload ->> 'low_confidence')::boolean;
    f_review  text    := NULLIF(p_payload ->> 'review_state', '');
    f_cells   boolean := COALESCE((p_payload ->> 'include_cells')::boolean, false);
    f_keys    text[]  := CASE WHEN p_payload ? 'keys' THEN ARRAY(SELECT jsonb_array_elements_text(p_payload -> 'keys')) END;
    lim       integer := LEAST(5000, GREATEST(1, COALESCE((p_payload ->> 'limit')::integer, 300)));
    off       integer := GREATEST(0, COALESCE((p_payload ->> 'offset')::integer, 0));
    total     bigint;
    defs      jsonb;
    vals      jsonb;
BEGIN
    IF et NOT IN ('FIB', 'SEM') THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment_type must be FIB or SEM');
    END IF;
    IF eq IS NULL OR NOT EXISTS (SELECT 1 FROM ionbeam_asset.equipment WHERE id = eq) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment not found');
    END IF;
    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    IF pid IS NOT NULL THEN
        SELECT * INTO prof FROM ionbeam_asset.calibration_profile WHERE id = pid;
    END IF;

    WITH page AS (
        SELECT d.id, count(*) OVER () AS total
          FROM ionbeam_asset.calibration_parameter_definition d
         WHERE d.equipment_type = et AND d.is_active
           AND (f_group IS NULL OR d.group_code = f_group OR d.group_code LIKE f_group || '.%')
           AND (f_q IS NULL OR position(f_q IN lower(d.display_name)) > 0 OR position(f_q IN lower(d.parameter_key)) > 0
                            OR position(f_q IN lower(COALESCE(d.vendor_name, ''))) > 0 OR position(f_q IN lower(d.description)) > 0)
           AND (f_class IS NULL OR d.param_class = f_class)
           AND (f_access IS NULL OR d.access_level = f_access)
           AND (f_undoc IS NULL OR ((NOT d.semantics_known OR d.param_class = 'undocumented') = f_undoc))
           AND (f_low IS NULL OR ((d.assign_conf = 'low') = f_low))
           AND (f_review IS NULL OR d.review_state = f_review)
           AND (f_cells OR d.table_code IS NULL)
           AND (f_keys IS NULL OR d.parameter_key = ANY (f_keys))
         ORDER BY d.sort_order
         LIMIT lim OFFSET off
    )
    SELECT COALESCE(max(page.total), 0),
           COALESCE(jsonb_agg(ionbeam_asset.fn_calibration_definition_json(
                        d, trim(both ' ' from COALESCE(pg.label || ' › ', '') || g.label), vmin.value_num, vmax.value_num)
                    ORDER BY d.sort_order), '[]'::jsonb),
           COALESCE(jsonb_agg(jsonb_build_object(
                        'definition_id', d.id, 'parameter_key', d.parameter_key,
                        'value', ionbeam_asset.fn_calibration_value_json(d.value_type, v.value_num, v.value_text),
                        'notes', v.notes, 'verified_at', v.verified_at, 'updated_at', v.update_date)
                    ORDER BY d.sort_order) FILTER (WHERE v.definition_id IS NOT NULL), '[]'::jsonb)
      INTO total, defs, vals
      FROM page
      JOIN ionbeam_asset.calibration_parameter_definition d ON d.id = page.id
      JOIN ionbeam_asset.calibration_group g ON g.equipment_type = d.equipment_type AND g.group_code = d.group_code
      LEFT JOIN ionbeam_asset.calibration_group pg ON pg.equipment_type = g.equipment_type AND pg.group_code = g.parent_code
      LEFT JOIN ionbeam_asset.calibration_value v ON v.profile_id = pid AND v.definition_id = d.id
      LEFT JOIN ionbeam_asset.calibration_parameter_definition dmin
             ON dmin.equipment_type = d.equipment_type AND dmin.parameter_key = d.limit_min_key
      LEFT JOIN ionbeam_asset.calibration_value vmin ON vmin.profile_id = pid AND vmin.definition_id = dmin.id
      LEFT JOIN ionbeam_asset.calibration_parameter_definition dmax
             ON dmax.equipment_type = d.equipment_type AND dmax.parameter_key = d.limit_max_key
      LEFT JOIN ionbeam_asset.calibration_value vmax ON vmax.profile_id = pid AND vmax.definition_id = dmax.id;

    RETURN jsonb_build_object('ok', true, 'equipment_id', eq, 'equipment_type', et,
        'profile', CASE WHEN pid IS NULL THEN NULL ELSE ionbeam_asset.fn_calibration_profile_json(prof) END,
        'definitions', defs, 'values', vals, 'total', total, 'limit', lim, 'offset', off);
END;
$$;

-- One table (matrix / list) with its cells.  payload: {equipment_id, equipment_type, table_code, profile_name?}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_get_calibration_table(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    eq   integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et   text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    tc   text    := btrim(COALESCE(p_payload ->> 'table_code', ''));
    pid  integer;
    prof ionbeam_asset.calibration_profile%ROWTYPE;
    t    ionbeam_asset.calibration_table%ROWTYPE;
    cells jsonb;
BEGIN
    IF et NOT IN ('FIB', 'SEM') THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment_type must be FIB or SEM');
    END IF;
    IF eq IS NULL OR NOT EXISTS (SELECT 1 FROM ionbeam_asset.equipment WHERE id = eq) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment not found');
    END IF;
    SELECT * INTO t FROM ionbeam_asset.calibration_table WHERE equipment_type = et AND table_code = tc;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'table not found');
    END IF;
    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    IF pid IS NOT NULL THEN
        SELECT * INTO prof FROM ionbeam_asset.calibration_profile WHERE id = pid;
    END IF;
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
               'row_key', d.row_key, 'col_key', d.col_key, 'definition_id', d.id, 'parameter_key', d.parameter_key,
               'display_name', d.display_name, 'value_type', d.value_type, 'unit', d.unit,
               'is_read_only', d.is_read_only, 'access_level', d.access_level, 'param_class', d.param_class,
               'semantics_known', d.semantics_known, 'assign_conf', d.assign_conf, 'review_state', d.review_state,
               'minimum_value', d.minimum_value, 'maximum_value', d.maximum_value, 'enum_options', COALESCE(d.enum_options, '[]'::jsonb),
               'default_value', d.default_value, 'source_reference', d.source_reference,
               'value', ionbeam_asset.fn_calibration_value_json(d.value_type, v.value_num, v.value_text))
           ORDER BY d.sort_order), '[]'::jsonb)
      INTO cells
      FROM ionbeam_asset.calibration_parameter_definition d
      LEFT JOIN ionbeam_asset.calibration_value v ON v.profile_id = pid AND v.definition_id = d.id
     WHERE d.equipment_type = et AND d.table_code = tc AND d.is_active;
    RETURN jsonb_build_object('ok', true, 'equipment_id', eq, 'equipment_type', et,
        'profile', CASE WHEN pid IS NULL THEN NULL ELSE ionbeam_asset.fn_calibration_profile_json(prof) END,
        'table', jsonb_build_object('table_code', t.table_code, 'label', t.label, 'kind', t.kind, 'group_code', t.group_code,
                                    'row_header', t.row_header, 'col_header', t.col_header, 'note', t.note,
                                    'rows', t.layout -> 'rows', 'cols', t.layout -> 'cols'),
        'cells', cells);
END;
$$;

-- Revision list (newest first).  payload: {equipment_id, equipment_type, profile_name?, parameter_key?, limit?, offset?}
-- Each item: {revision, snapshot (values changed by this revision), created_at, created_by, created_by_name, kind, reason,
--             source_ref, changed_count, changes (first 50), changes_truncated}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_list_equipment_calibration_history(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    eq   integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et   text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    pk   text    := NULLIF(btrim(COALESCE(p_payload ->> 'parameter_key', '')), '');
    lim  integer := LEAST(200, GREATEST(1, COALESCE((p_payload ->> 'limit')::integer, 25)));
    off  integer := GREATEST(0, COALESCE((p_payload ->> 'offset')::integer, 0));
    pid  integer;
BEGIN
    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    IF pid IS NULL THEN
        RETURN '[]'::jsonb;
    END IF;
    RETURN COALESCE((
        SELECT jsonb_agg(row_json ORDER BY rev DESC) FROM (
            SELECT r.revision AS rev, jsonb_build_object(
                'revision', r.revision,
                'snapshot', COALESCE((SELECT jsonb_object_agg(c ->> 'parameter_key', c -> 'new')
                                        FROM (SELECT c FROM jsonb_array_elements(r.changes) c
                                               WHERE pk IS NULL OR c ->> 'parameter_key' = pk LIMIT 50) s(c)), '{}'::jsonb),
                'created_at', r.created_at, 'created_by', r.created_by,
                'created_by_name', (SELECT btrim(u.login_name::text) FROM iobeam_admin."user" u WHERE u.id = r.created_by),
                'kind', r.kind, 'reason', r.reason, 'source_ref', r.source_ref, 'changed_count', r.changed_count,
                'changes', COALESCE((SELECT jsonb_agg(c) FROM (SELECT c FROM jsonb_array_elements(r.changes) c
                                                                WHERE pk IS NULL OR c ->> 'parameter_key' = pk LIMIT 50) s(c)), '[]'::jsonb),
                'changes_truncated', (SELECT count(*) FROM jsonb_array_elements(r.changes) c
                                       WHERE pk IS NULL OR c ->> 'parameter_key' = pk) > 50
            ) AS row_json
              FROM ionbeam_asset.calibration_revision r
             WHERE r.profile_id = pid
               AND (pk IS NULL OR r.changes @> jsonb_build_array(jsonb_build_object('parameter_key', pk)))
             ORDER BY r.revision DESC LIMIT lim OFFSET off
        ) q), '[]'::jsonb);
END;
$$;

-- One revision in full.  payload: {equipment_id, equipment_type, profile_name?, revision, include_snapshot?}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_get_calibration_revision(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql STABLE AS $$
DECLARE
    pid integer := ionbeam_asset.fn_calibration_find_profile(
        NULLIF(p_payload ->> 'equipment_id', '')::integer, upper(btrim(COALESCE(p_payload ->> 'equipment_type', ''))), p_payload ->> 'profile_name');
    r   ionbeam_asset.calibration_revision%ROWTYPE;
BEGIN
    SELECT * INTO r FROM ionbeam_asset.calibration_revision
     WHERE profile_id = pid AND revision = NULLIF(p_payload ->> 'revision', '')::integer;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'revision not found');
    END IF;
    RETURN jsonb_build_object('ok', true, 'revision', r.revision, 'kind', r.kind, 'reason', r.reason, 'source_ref', r.source_ref,
        'created_at', r.created_at, 'created_by', r.created_by, 'changed_count', r.changed_count, 'changes', r.changes,
        'snapshot', CASE WHEN COALESCE((p_payload ->> 'include_snapshot')::boolean, false) THEN r.full_snapshot END);
END;
$$;

-- =====================================================================================================
-- write path (public)
-- =====================================================================================================
-- payload: {equipment_id, equipment_type, profile_name?, notes?, actor_user_id?, actor_role?, reason?,
--           expected_revision?, acknowledge_risk?, dry_run?, values:[{parameter_key, value, notes?, verified?, clear?}]}
-- returns the bundle of the parameters that were written, plus {result:{revision, changed, unchanged, changes}}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_upsert_equipment_calibration(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    eq       integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et       text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    pname    text    := COALESCE(NULLIF(btrim(COALESCE(p_payload ->> 'profile_name', '')), ''), 'default');
    actor    integer := NULLIF(p_payload ->> 'actor_user_id', '')::integer;
    pid      integer;
    created  boolean := false;
    res      jsonb;
    bundle   jsonb;
BEGIN
    IF et NOT IN ('FIB', 'SEM') THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment_type must be FIB or SEM');
    END IF;
    IF eq IS NULL OR NOT EXISTS (SELECT 1 FROM ionbeam_asset.equipment WHERE id = eq) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment not found');
    END IF;
    IF actor IS NOT NULL AND NOT EXISTS (SELECT 1 FROM iobeam_admin."user" WHERE id = actor) THEN
        actor := NULL;
    END IF;

    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, COALESCE(p_payload ->> 'profile_name', NULL));
    IF pid IS NULL THEN
        INSERT INTO ionbeam_asset.calibration_profile (equipment_id, equipment_type, profile_name, is_active, updated_by)
        VALUES (eq, et, pname,
                NOT EXISTS (SELECT 1 FROM ionbeam_asset.calibration_profile WHERE equipment_id = eq AND equipment_type = et AND is_active),
                actor)
        RETURNING id INTO pid;
        created := true;
    END IF;

    res := ionbeam_asset.fn_calibration_apply(
        pid, p_payload -> 'values', COALESCE(NULLIF(p_payload ->> 'kind', ''), 'edit'), p_payload ->> 'reason', actor,
        COALESCE((p_payload ->> 'actor_role')::integer, 0), COALESCE((p_payload ->> 'acknowledge_risk')::boolean, false),
        NULLIF(p_payload ->> 'expected_revision', '')::integer, p_payload ->> 'source_ref', true, true,
        COALESCE((p_payload ->> 'dry_run')::boolean, false));

    IF NOT (res ->> 'ok')::boolean THEN
        IF created THEN
            DELETE FROM ionbeam_asset.calibration_profile WHERE id = pid AND revision = 0;
        END IF;
        RETURN res;
    END IF;

    IF p_payload ? 'notes' AND NOT COALESCE((p_payload ->> 'dry_run')::boolean, false) THEN
        UPDATE ionbeam_asset.calibration_profile SET notes = COALESCE(p_payload ->> 'notes', '') WHERE id = pid;
    END IF;

    bundle := ionbeam_asset.fn_get_equipment_calibration(jsonb_build_object(
        'equipment_id', eq, 'equipment_type', et, 'profile_name', (SELECT profile_name FROM ionbeam_asset.calibration_profile WHERE id = pid),
        'include_cells', true,
        'keys', COALESCE((SELECT jsonb_agg(v ->> 'parameter_key') FROM jsonb_array_elements(p_payload -> 'values') v), '[]'::jsonb)));
    RETURN bundle || jsonb_build_object('result', res);
END;
$$;

-- payload: {equipment_id, equipment_type, profile_name?, revision, actor_user_id?, actor_role?, reason?, acknowledge_risk?, dry_run?}
-- Writes a NEW revision (kind 'restore') that brings every parameter back to its value at `revision`.
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_restore_equipment_calibration_revision(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    eq      integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et      text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    rev     integer := NULLIF(p_payload ->> 'revision', '')::integer;
    actor   integer := NULLIF(p_payload ->> 'actor_user_id', '')::integer;
    pid     integer;
    snap    jsonb;
    items   jsonb;
BEGIN
    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    IF pid IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'profile not found');
    END IF;
    SELECT full_snapshot INTO snap FROM ionbeam_asset.calibration_revision WHERE profile_id = pid AND revision = rev;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'revision not found');
    END IF;
    IF actor IS NOT NULL AND NOT EXISTS (SELECT 1 FROM iobeam_admin."user" WHERE id = actor) THEN
        actor := NULL;
    END IF;
    items := COALESCE((SELECT jsonb_agg(jsonb_build_object('parameter_key', k, 'value', v)) FROM jsonb_each(snap) e(k, v)), '[]'::jsonb)
          || COALESCE((SELECT jsonb_agg(jsonb_build_object('parameter_key', d.parameter_key, 'clear', true))
                         FROM ionbeam_asset.calibration_value cv
                         JOIN ionbeam_asset.calibration_parameter_definition d ON d.id = cv.definition_id
                        WHERE cv.profile_id = pid AND (cv.value_num IS NOT NULL OR cv.value_text IS NOT NULL)
                          AND NOT (snap ? d.parameter_key)), '[]'::jsonb);
    RETURN ionbeam_asset.fn_calibration_apply(
        pid, items, 'restore', COALESCE(NULLIF(p_payload ->> 'reason', ''), 'restore revision ' || rev), actor,
        COALESCE((p_payload ->> 'actor_role')::integer, 0), COALESCE((p_payload ->> 'acknowledge_risk')::boolean, false),
        NULLIF(p_payload ->> 'expected_revision', '')::integer, 'revision ' || rev, true, false,
        COALESCE((p_payload ->> 'dry_run')::boolean, false));
END;
$$;

-- Vendor machine-data / calibration CSV import.  The backend parses the file; this function matches lines to catalog entries.
-- payload: {equipment_id, equipment_type, profile_name?, file_name, dry_run?, actor_user_id?, actor_role, reason?, acknowledge_risk?,
--           items:[{kind:'int'|'float', slot, raw, symbol?}  |  {path, raw}  |  {parameter_key, raw}]}
-- {parameter_key, raw} items come from a calibration CSV (Export CSV format) and are matched by catalog key.
-- Needs role >= 2 (developer / service). Lines with no catalog entry (credentials, debug flags, UI prefs ...) are
-- counted and dropped - never stored. Values that do not fit the parameter type are listed under `rejected`.
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_import_equipment_calibration(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    eq        integer := NULLIF(p_payload ->> 'equipment_id', '')::integer;
    et        text    := upper(btrim(COALESCE(p_payload ->> 'equipment_type', '')));
    role      integer := COALESCE((p_payload ->> 'actor_role')::integer, 0);
    dry       boolean := COALESCE((p_payload ->> 'dry_run')::boolean, true);
    actor     integer := NULLIF(p_payload ->> 'actor_user_id', '')::integer;
    pname     text    := COALESCE(NULLIF(btrim(COALESCE(p_payload ->> 'profile_name', '')), ''), 'default');
    it        jsonb;
    d         ionbeam_asset.calibration_parameter_definition%ROWTYPE;
    c         jsonb;
    items     jsonb := '[]'::jsonb;
    unmatched jsonb := '[]'::jsonb;
    rejected  jsonb := '[]'::jsonb;
    n_unmatched integer := 0;
    n_rejected  integer := 0;
    n_matched   integer := 0;
    n_warn      integer := 0;
    n_other     integer := 0;
    warns     jsonb := '[]'::jsonb;
    ident     text;
    pid       integer;
    created   boolean := false;
    preview   jsonb;
    risky     integer;
    res       jsonb;
BEGIN
    IF et NOT IN ('FIB', 'SEM') THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment_type must be FIB or SEM');
    END IF;
    IF eq IS NULL OR NOT EXISTS (SELECT 1 FROM ionbeam_asset.equipment WHERE id = eq) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'equipment not found');
    END IF;
    IF role < 2 THEN
        RETURN jsonb_build_object('ok', false, 'error', 'forbidden_role', 'message', 'importing a vendor file needs role 2 (developer) or higher');
    END IF;
    IF actor IS NOT NULL AND NOT EXISTS (SELECT 1 FROM iobeam_admin."user" WHERE id = actor) THEN
        actor := NULL;
    END IF;

    FOR it IN SELECT value FROM jsonb_array_elements(COALESCE(p_payload -> 'items', '[]'::jsonb))
    LOOP
        d := NULL;
        IF it ? 'parameter_key' THEN
            -- a row of a calibration CSV (Export CSV format): matched by its catalog key, not by a vendor slot / path
            ident := it ->> 'parameter_key';
            SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition
             WHERE equipment_type = et AND parameter_key = ident AND is_active LIMIT 1;
        ELSIF it ? 'path' THEN
            ident := it ->> 'path';
            SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition
             WHERE equipment_type = et AND source_kind = 'reg' AND source_path = ident AND is_active LIMIT 1;
        ELSE
            ident := (it ->> 'kind') || ' ' || (it ->> 'slot');
            SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition
             WHERE equipment_type = et AND source_kind = (it ->> 'kind') AND source_slot = (it ->> 'slot')::integer AND is_active LIMIT 1;
        END IF;
        IF d.id IS NULL THEN
            IF EXISTS (SELECT 1 FROM ionbeam_asset.calibration_parameter_definition o
                        WHERE o.equipment_type <> et AND o.is_active
                          AND ((it ? 'parameter_key' AND o.parameter_key = ident)
                               OR (it ? 'path' AND NOT it ? 'parameter_key' AND o.source_kind = 'reg' AND o.source_path = ident))) THEN
                -- a registry value that belongs to the other column (FIB vs SEM) of the same export. Machine-data slots are
                -- NOT compared this way: icmd.TXT and md.TXT are different files that reuse the same slot numbers.
                n_other := n_other + 1;
                CONTINUE;
            END IF;
            n_unmatched := n_unmatched + 1;
            IF n_unmatched <= 30 THEN unmatched := unmatched || to_jsonb(ident); END IF;
            CONTINUE;
        END IF;
        -- wrong-file guard: icmd.TXT and md.TXT reuse the same slot numbers, so when the parser saw a vendor symbol
        -- it must be the symbol the catalog has for that slot
        IF NOT it ? 'path' AND NOT it ? 'parameter_key' AND NULLIF(it ->> 'symbol', '') IS NOT NULL
           AND (it ->> 'symbol') IS DISTINCT FROM d.vendor_name THEN
            n_rejected := n_rejected + 1;
            IF n_rejected <= 30 THEN
                rejected := rejected || jsonb_build_object('parameter_key', d.parameter_key, 'raw', it ->> 'raw',
                    'message', format('vendor symbol %s in the file, but the catalog has %s for %s slot %s - is this the machine-data file of this column?',
                                      it ->> 'symbol', COALESCE(d.vendor_name, 'no name'), it ->> 'kind', it ->> 'slot'));
            END IF;
            CONTINUE;
        END IF;
        c := ionbeam_asset.fn_calibration_coerce(d, to_jsonb(COALESCE(it ->> 'raw', '')), false);
        IF (c ->> 'ok')::boolean AND d.value_type = 'enum' AND NOT EXISTS (
               SELECT 1 FROM jsonb_array_elements(d.enum_options) o WHERE (o ->> 'value')::numeric = (c ->> 'num')::numeric) THEN
            n_warn := n_warn + 1;
            IF n_warn <= 30 THEN
                warns := warns || jsonb_build_object('parameter_key', d.parameter_key, 'raw', it ->> 'raw',
                             'message', 'value is not in the vendor''s documented list; imported as found');
            END IF;
        END IF;
        IF NOT (c ->> 'ok')::boolean THEN
            n_rejected := n_rejected + 1;
            IF n_rejected <= 30 THEN
                rejected := rejected || jsonb_build_object('parameter_key', d.parameter_key, 'raw', it ->> 'raw', 'message', c ->> 'message');
            END IF;
            CONTINUE;
        END IF;
        n_matched := n_matched + 1;
        items := items || jsonb_build_object('parameter_key', d.parameter_key,
                    'value', CASE WHEN d.value_type = 'text' THEN to_jsonb(c ->> 'text')
                                  WHEN d.value_type = 'boolean' THEN to_jsonb((c ->> 'num')::numeric <> 0)
                                  ELSE to_jsonb((c ->> 'num')::numeric) END);
    END LOOP;

    pid := ionbeam_asset.fn_calibration_find_profile(eq, et, p_payload ->> 'profile_name');
    IF pid IS NULL THEN
        INSERT INTO ionbeam_asset.calibration_profile (equipment_id, equipment_type, profile_name, is_active, updated_by)
        VALUES (eq, et, pname,
                NOT EXISTS (SELECT 1 FROM ionbeam_asset.calibration_profile WHERE equipment_id = eq AND equipment_type = et AND is_active),
                actor)
        RETURNING id INTO pid;
        created := true;
    END IF;

    preview := ionbeam_asset.fn_calibration_apply(pid, items, 'import', p_payload ->> 'reason', actor, role, true,
                                                  NULL, p_payload ->> 'file_name', false, false, true);
    IF NOT (preview ->> 'ok')::boolean THEN
        IF created THEN DELETE FROM ionbeam_asset.calibration_profile WHERE id = pid AND revision = 0; END IF;
        RETURN preview;
    END IF;

    SELECT count(*) INTO risky
      FROM jsonb_array_elements(preview -> 'changes') ch
      JOIN ionbeam_asset.calibration_parameter_definition x ON x.equipment_type = et AND x.parameter_key = ch ->> 'parameter_key'
     WHERE ionbeam_asset.fn_calibration_needs_ack(x) IS NOT NULL;

    IF dry THEN
        IF created THEN DELETE FROM ionbeam_asset.calibration_profile WHERE id = pid AND revision = 0; END IF;
        RETURN jsonb_build_object('ok', true, 'dry_run', true, 'matched', n_matched, 'unmatched_count', n_unmatched,
            'unmatched', unmatched, 'other_type_count', n_other, 'rejected_count', n_rejected, 'rejected', rejected,
            'warning_count', n_warn, 'warnings', warns,
            'changed', preview -> 'changed', 'unchanged', preview -> 'unchanged', 'risky_changed', risky,
            'changes', COALESCE((SELECT jsonb_agg(c2) FROM (SELECT c2 FROM jsonb_array_elements(preview -> 'changes') c2 LIMIT 200) s(c2)), '[]'::jsonb),
            'revision', preview -> 'revision');
    END IF;

    -- A commit is all-or-nothing for recognised parameters. The dry run above reports every rejected value so the
    -- operator can correct the source file first; never silently save only the valid subset.
    IF n_rejected > 0 THEN
        IF created THEN DELETE FROM ionbeam_asset.calibration_profile WHERE id = pid AND revision = 0; END IF;
        RETURN jsonb_build_object('ok', false, 'error', 'validation_failed',
            'message', format('%s recognised value(s) failed validation; nothing was imported', n_rejected),
            'errors', rejected, 'rejected_count', n_rejected);
    END IF;

    IF risky > 0 AND NOT COALESCE((p_payload ->> 'acknowledge_risk')::boolean, false) THEN
        IF created THEN DELETE FROM ionbeam_asset.calibration_profile WHERE id = pid AND revision = 0; END IF;
        RETURN jsonb_build_object('ok', false, 'error', 'risk_ack_required',
            'errors', jsonb_build_array(jsonb_build_object('code', 'risk_ack_required',
                'message', format('%s of the changed values are vendor-undocumented, fixed or low-confidence parameters', risky))));
    END IF;

    res := ionbeam_asset.fn_calibration_apply(pid, items, 'import', p_payload ->> 'reason', actor, role, true, NULL,
                                              p_payload ->> 'file_name', false, false, false);
    RETURN res || jsonb_build_object('matched', n_matched, 'unmatched_count', n_unmatched, 'rejected_count', n_rejected,
                                     'other_type_count', n_other, 'warning_count', n_warn, 'warnings', warns, 'risky_changed', risky);
END;
$$;

-- Catalog metadata edit (admin).  payload: {id, actor_user_id?, actor_role, display_name?, description?, unit?,
--           review_state?, param_class?, semantics_known?, is_active?}
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_update_calibration_definition(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    did     integer := NULLIF(p_payload ->> 'id', '')::integer;
    actor   integer := NULLIF(p_payload ->> 'actor_user_id', '')::integer;
    d       ionbeam_asset.calibration_parameter_definition%ROWTYPE;
    n       ionbeam_asset.calibration_parameter_definition%ROWTYPE;
    manual  boolean;
BEGIN
    IF COALESCE((p_payload ->> 'actor_role')::integer, 0) < 3 THEN
        RETURN jsonb_build_object('ok', false, 'error', 'forbidden_role', 'message', 'editing the catalog needs role 3 (admin)');
    END IF;
    SELECT * INTO d FROM ionbeam_asset.calibration_parameter_definition WHERE id = did FOR UPDATE;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'parameter not found');
    END IF;
    IF actor IS NOT NULL AND NOT EXISTS (SELECT 1 FROM iobeam_admin."user" WHERE id = actor) THEN
        actor := NULL;
    END IF;
    n := d;
    IF p_payload ? 'display_name' THEN n.display_name := left(btrim(p_payload ->> 'display_name'), 300); END IF;
    IF p_payload ? 'description'  THEN n.description  := COALESCE(p_payload ->> 'description', ''); END IF;
    IF p_payload ? 'unit'         THEN n.unit         := left(btrim(COALESCE(p_payload ->> 'unit', '')), 30); END IF;
    IF p_payload ? 'param_class'  THEN n.param_class  := p_payload ->> 'param_class'; END IF;
    IF p_payload ? 'semantics_known' THEN n.semantics_known := (p_payload ->> 'semantics_known')::boolean; END IF;
    IF p_payload ? 'review_state' THEN n.review_state := p_payload ->> 'review_state'; END IF;
    IF p_payload ? 'is_active'    THEN n.is_active    := (p_payload ->> 'is_active')::boolean; END IF;
    IF n.display_name = '' THEN
        RETURN jsonb_build_object('ok', false, 'error', 'display_name must not be empty');
    END IF;
    manual := n.display_name <> d.display_name OR n.description <> d.description OR n.unit <> d.unit
              OR n.param_class <> d.param_class OR n.semantics_known <> d.semantics_known;
    IF manual THEN
        n.assign_basis := 'manual';
        IF n.review_state = 'imported' THEN n.review_state := 'reviewed'; END IF;   -- a human edit must survive a catalog re-seed
        IF n.semantics_known AND NOT d.semantics_known THEN n.assign_conf := 'medium'; END IF;   -- a human named it; still not vendor-confirmed
    END IF;
    UPDATE ionbeam_asset.calibration_parameter_definition
       SET display_name = n.display_name, description = n.description, unit = n.unit, param_class = n.param_class,
           semantics_known = n.semantics_known, review_state = n.review_state, is_active = n.is_active,
           assign_basis = n.assign_basis, assign_conf = n.assign_conf
     WHERE id = did;
    INSERT INTO ionbeam_asset.calibration_definition_change (definition_id, changed_by, before_value, after_value)
    VALUES (did, actor,
            jsonb_build_object('display_name', d.display_name, 'description', d.description, 'unit', d.unit, 'param_class', d.param_class,
                               'semantics_known', d.semantics_known, 'review_state', d.review_state, 'is_active', d.is_active),
            jsonb_build_object('display_name', n.display_name, 'description', n.description, 'unit', n.unit, 'param_class', n.param_class,
                               'semantics_known', n.semantics_known, 'review_state', n.review_state, 'is_active', n.is_active));
    RETURN jsonb_build_object('ok', true, 'definition', ionbeam_asset.fn_calibration_definition_json(
        (SELECT x FROM ionbeam_asset.calibration_parameter_definition x WHERE x.id = did), ''));
END;
$$;

-- =====================================================================================================
-- catalog seeding (idempotent).  payload: {groups:[...], tables:[...], definitions:[...]}  (see 004_calibration_seed.sql)
-- Re-running refreshes machine-derived columns; a human-edited name / description / unit is kept once
-- review_state has moved past 'imported'.
-- =====================================================================================================
CREATE OR REPLACE FUNCTION ionbeam_asset.fn_seed_calibration_catalog(p_payload jsonb)
RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
    n_groups integer; n_tables integer; n_defs integer;
BEGIN
    INSERT INTO ionbeam_asset.calibration_group (equipment_type, group_code, parent_code, label, sort_order)
    SELECT g.equipment_type, g.group_code, g.parent_code, g.label, g.sort_order
      FROM jsonb_to_recordset(p_payload -> 'groups')
           AS g(equipment_type text, group_code text, parent_code text, label text, sort_order integer)
    ON CONFLICT (equipment_type, group_code) DO UPDATE
       SET parent_code = EXCLUDED.parent_code, label = EXCLUDED.label, sort_order = EXCLUDED.sort_order;
    GET DIAGNOSTICS n_groups = ROW_COUNT;

    INSERT INTO ionbeam_asset.calibration_table (equipment_type, table_code, group_code, label, kind, row_header, col_header, note, layout)
    SELECT t.equipment_type, t.table_code, t.group_code, t.label, t.kind, t.row_header, t.col_header, t.note, t.layout
      FROM jsonb_to_recordset(p_payload -> 'tables')
           AS t(equipment_type text, table_code text, group_code text, label text, kind text, row_header text,
                col_header text, note text, layout jsonb)
    ON CONFLICT (equipment_type, table_code) DO UPDATE
       SET group_code = EXCLUDED.group_code, label = EXCLUDED.label, kind = EXCLUDED.kind, row_header = EXCLUDED.row_header,
           col_header = EXCLUDED.col_header, note = EXCLUDED.note, layout = EXCLUDED.layout;
    GET DIAGNOSTICS n_tables = ROW_COUNT;

    INSERT INTO ionbeam_asset.calibration_parameter_definition AS d (
        equipment_type, parameter_key, group_code, vendor_name, display_name, description, value_type, unit, unit_source,
        minimum_value, maximum_value, limit_min_key, limit_max_key, default_value, enum_options, param_class, access_level,
        is_read_only, shared_hardware, applicability, ui_widget, adjustment_no, table_code, row_key, col_key,
        source_vendor, source_document, source_url, source_reference, source_kind, source_slot, source_path, source_line,
        vendor_flags, semantics_known, assign_basis, assign_conf, sort_order)
    SELECT x.equipment_type, x.parameter_key, x.group_code, x.vendor_name, x.display_name, COALESCE(x.description, ''), x.value_type,
           COALESCE(x.unit, ''), x.unit_source, x.minimum_value, x.maximum_value, x.limit_min_key, x.limit_max_key, x.default_value,
           x.enum_options, x.param_class, x.access_level, COALESCE(x.is_read_only, false), COALESCE(x.shared_hardware, false),
           COALESCE(ARRAY(SELECT jsonb_array_elements_text(x.applicability)), ARRAY[]::text[]), COALESCE(x.ui_widget, 'number'),
           x.adjustment_no, x.table_code, x.row_key, x.col_key,
           COALESCE(x.source_vendor, ''), COALESCE(x.source_document, ''), COALESCE(x.source_url, ''), COALESCE(x.source_reference, ''),
           x.source_kind, x.source_slot, x.source_path, x.source_line, x.vendor_flags, COALESCE(x.semantics_known, true),
           x.assign_basis, x.assign_conf, COALESCE(x.sort_order, 0)
      FROM jsonb_to_recordset(p_payload -> 'definitions') AS x(
           equipment_type text, parameter_key text, group_code text, vendor_name text, display_name text, description text,
           value_type text, unit text, unit_source text, minimum_value double precision, maximum_value double precision,
           limit_min_key text, limit_max_key text, default_value jsonb, enum_options jsonb, param_class text, access_level text,
           is_read_only boolean, shared_hardware boolean, applicability jsonb, ui_widget text, adjustment_no text,
           table_code text, row_key text, col_key text, source_vendor text, source_document text, source_url text,
           source_reference text, source_kind text, source_slot integer, source_path text, source_line integer,
           vendor_flags text, semantics_known boolean, assign_basis text, assign_conf text, sort_order integer)
    ON CONFLICT (equipment_type, parameter_key) DO UPDATE SET
        group_code = EXCLUDED.group_code, vendor_name = EXCLUDED.vendor_name,
        display_name = CASE WHEN d.review_state = 'imported' THEN EXCLUDED.display_name ELSE d.display_name END,
        description  = CASE WHEN d.review_state = 'imported' THEN EXCLUDED.description  ELSE d.description  END,
        unit         = CASE WHEN d.review_state = 'imported' THEN EXCLUDED.unit         ELSE d.unit         END,
        param_class  = CASE WHEN d.assign_basis = 'manual' THEN d.param_class ELSE EXCLUDED.param_class END,
        semantics_known = CASE WHEN d.assign_basis = 'manual' THEN d.semantics_known ELSE EXCLUDED.semantics_known END,
        assign_basis = CASE WHEN d.assign_basis = 'manual' THEN d.assign_basis ELSE EXCLUDED.assign_basis END,
        assign_conf  = CASE WHEN d.assign_basis = 'manual' THEN d.assign_conf ELSE EXCLUDED.assign_conf END,
        value_type = EXCLUDED.value_type, unit_source = EXCLUDED.unit_source, minimum_value = EXCLUDED.minimum_value,
        maximum_value = EXCLUDED.maximum_value, limit_min_key = EXCLUDED.limit_min_key, limit_max_key = EXCLUDED.limit_max_key,
        default_value = EXCLUDED.default_value, enum_options = EXCLUDED.enum_options, access_level = EXCLUDED.access_level,
        is_read_only = EXCLUDED.is_read_only, shared_hardware = EXCLUDED.shared_hardware, applicability = EXCLUDED.applicability,
        ui_widget = EXCLUDED.ui_widget, adjustment_no = EXCLUDED.adjustment_no, table_code = EXCLUDED.table_code,
        row_key = EXCLUDED.row_key, col_key = EXCLUDED.col_key, source_vendor = EXCLUDED.source_vendor,
        source_document = EXCLUDED.source_document, source_url = EXCLUDED.source_url, source_reference = EXCLUDED.source_reference,
        source_kind = EXCLUDED.source_kind, source_slot = EXCLUDED.source_slot, source_path = EXCLUDED.source_path,
        source_line = EXCLUDED.source_line, vendor_flags = EXCLUDED.vendor_flags, sort_order = EXCLUDED.sort_order;
    GET DIAGNOSTICS n_defs = ROW_COUNT;
    RETURN jsonb_build_object('ok', true, 'groups', n_groups, 'tables', n_tables, 'definitions', n_defs);
END;
$$;
