[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iobeam-development"
version = "0.1.0"
description = "Development project for AutomationPy and EsmBeamController"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
# Explicitly defining the packages prevents the "Multiple top-level packages" error
packages = ["AutomationPy", "LoadFPGAImage", "GlasgowDataIO"]

[tool.pytest.ini_options]
pythonpath = [
  "GlasgowDataIO"
]
filterwarnings = [
    "ignore:.*reset=.*:DeprecationWarning",
    "ignore:Use \"with USBContext() as context\":DeprecationWarning",
    "ignore::DeprecationWarning:glasgow.*"
]