"""Regenerate ../Sql/004_calibration_seed.sql from the vendor machine-data files.

    python build_seed.py <dir containing icmd.TXT, md.TXT, UI1280reg.txt>

Also writes calibration_catalog_report.json (statistics + everything that was deliberately left out, e.g. credentials).
Run it again whenever the taxonomy or the parsers change; loading the SQL is idempotent.
"""
from __future__ import annotations
import json, os, sys

from calibration_catalog import catalog_builder, md_parser, registry_parser, seed_export

HERE = os.path.dirname(os.path.abspath(__file__))
SQL_OUT = os.path.join(HERE, "..", "Sql", "004_calibration_seed.sql")
REPORT_OUT = os.path.join(HERE, "calibration_catalog_report.json")


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    src = argv[1]
    fib = md_parser.parse_md_file(os.path.join(src, "icmd.TXT"), "icmd.TXT")
    sem = md_parser.parse_md_file(os.path.join(src, "md.TXT"), "md.TXT")
    _, reg = registry_parser.parse_registry_file(os.path.join(src, "UI1280reg.txt"))
    cat = catalog_builder.build_catalog(fib, sem, reg)
    seed = seed_export.to_seed(cat)
    header = ("-- GENERATED by IobeamAdmin/CalibrationCatalog/build_seed.py - do not edit by hand.\n"
              f"-- {len(seed['definitions'])} parameter definitions, {len(seed['tables'])} table layouts, {len(seed['groups'])} groups.\n"
              "-- Loaded by ionbeam-web/backend (npm run db:seed:calibration). Idempotent.\n")
    with open(SQL_OUT, "w", encoding="utf-8") as fh:
        fh.write(seed_export.to_sql(seed, header))
    with open(REPORT_OUT, "w", encoding="utf-8") as fh:
        json.dump(dict(stats=cat["stats"], excluded=cat["excluded"]), fh, indent=1, default=str)
    print(json.dumps(cat["stats"], indent=1, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
