<#
.SYNOPSIS
  Install the Ion Beam native desktop app on Windows from a Development
  checkout (or a bundle made by scripts/build.py, which has the same layout).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File ionbeam-native\scripts\install_windows.ps1
  powershell -ExecutionPolicy Bypass -File ionbeam-native\scripts\install_windows.ps1 -Venv C:\Operations\.venv -Dev -NoShortcut

.NOTES
  Idempotent. The Glasgow board must be bound to the WinUSB driver (Zadig) for
  hardware scans; the emulator (-SkipSmoke off) needs no driver.
#>
[CmdletBinding()]
param(
  [string]$Venv = "",
  [string]$Python = "",
  [switch]$Dev,
  [switch]$NoShortcut,
  [switch]$SkipSmoke,
  [switch]$Uninstall
)
$ErrorActionPreference = "Stop"

$AppRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$DevRoot = (Resolve-Path (Join-Path $AppRoot "..")).Path
if (-not $Venv) { $Venv = Join-Path $AppRoot ".venv" }
$InstallDir = Join-Path $env:LOCALAPPDATA "IonBeamNative"
$Launcher = Join-Path $InstallDir "ionbeam-native.cmd"
$ShortcutPath = Join-Path ([Environment]::GetFolderPath("Programs")) "Ion Beam (native).lnk"

function Say($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "warning: $msg" -ForegroundColor Yellow }
function Die($msg) { Write-Host "error: $msg" -ForegroundColor Red; exit 1 }
function Invoke-Checked([string]$exe, [string[]]$argv) {
  & $exe @argv
  if ($LASTEXITCODE -ne 0) { Die "$exe $($argv -join ' ') failed (exit $LASTEXITCODE)" }
}

if ($Uninstall) {
  Remove-Item -Force -ErrorAction SilentlyContinue $Launcher, $ShortcutPath
  Say "removed launcher and Start-menu shortcut (venv kept: $Venv)"
  exit 0
}

foreach ($d in "GlasgowDataIO", "glasgow_service", "AutomationPy") {
  if (-not (Test-Path (Join-Path $DevRoot $d))) { Die "$DevRoot\$d not found - run this from a Development checkout or bundle" }
}

# ---------------------------------------------------------------- interpreter
if (-not $Python) {
  if (Get-Command py -ErrorAction SilentlyContinue) { $Python = "py" } else { $Python = "python" }
}
$pyArgs = @()
if ($Python -eq "py") { $pyArgs = @("-3") }
& $Python @pyArgs -c "import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)"
if ($LASTEXITCODE -ne 0) { Die "Python >= 3.10 is required (winget install Python.Python.3.12)" }

# ---------------------------------------------------------------- venv + packages
$VPy = Join-Path $Venv "Scripts\python.exe"
$VPyw = Join-Path $Venv "Scripts\pythonw.exe"
if (-not (Test-Path $VPy)) {
  Say "creating virtualenv $Venv"
  Invoke-Checked $Python ($pyArgs + @("-m", "venv", $Venv))
}
Say "installing pinned requirements"
Invoke-Checked $VPy @("-m", "pip", "install", "--upgrade", "--quiet", "pip")
Invoke-Checked $VPy @("-m", "pip", "install", "--quiet", "-r", (Join-Path $AppRoot "requirements.txt"))
if ($Dev) { Invoke-Checked $VPy @("-m", "pip", "install", "--quiet", "-r", (Join-Path $AppRoot "requirements-dev.txt")) }
Say "installing ionbeam-native (editable, from $AppRoot)"
Invoke-Checked $VPy @("-m", "pip", "install", "--quiet", "--no-deps", "-e", $AppRoot)

# ---------------------------------------------------------------- verify
Say "verifying imports"
$env:IONBEAM_DEVELOPMENT_ROOT = $DevRoot
$verifyDir = New-Item -ItemType Directory -Path (Join-Path ([IO.Path]::GetTempPath()) ("ionbeam-verify-" + [guid]::NewGuid()))
Push-Location $verifyDir
try {
  $env:QT_QPA_PLATFORM = "offscreen"
  Invoke-Checked $VPy @("-c", "import ionbeam_native.engine.engine, ionbeam_native.ui.main_window; print('    imports ok')")
} finally {
  Remove-Item Env:QT_QPA_PLATFORM -ErrorAction SilentlyContinue
  Pop-Location
  Remove-Item -Recurse -Force $verifyDir -ErrorAction SilentlyContinue
}

# ---------------------------------------------------------------- launcher + shortcut
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
$config = Join-Path $DevRoot "GlasgowDataIO\Json\streamData.json"
@"
@echo off
rem generated by ionbeam-native\scripts\install_windows.ps1
if not defined IONBEAM_DEVELOPMENT_ROOT set "IONBEAM_DEVELOPMENT_ROOT=$DevRoot"
if not defined GLASGOW_CONFIG if exist "$config" set "GLASGOW_CONFIG=$config"
"$VPy" -m ionbeam_native %*
"@ | Set-Content -Encoding ASCII $Launcher
Say "launcher: $Launcher"

if (-not $NoShortcut) {
  $icon = Join-Path $AppRoot "ionbeam_native\resources\images\brand-logo.png"
  $shell = New-Object -ComObject WScript.Shell
  $lnk = $shell.CreateShortcut($ShortcutPath)
  $lnk.TargetPath = $VPyw
  $lnk.Arguments = "-m ionbeam_native"
  $lnk.WorkingDirectory = $InstallDir
  $lnk.Description = "Ion Beam control console - native desktop client"
  $lnk.Save()
  # pythonw has no console; the environment comes from the per-user variables below
  [Environment]::SetEnvironmentVariable("IONBEAM_DEVELOPMENT_ROOT", $DevRoot, "User")
  if ((Test-Path $config) -and -not [Environment]::GetEnvironmentVariable("GLASGOW_CONFIG", "User")) {
    [Environment]::SetEnvironmentVariable("GLASGOW_CONFIG", $config, "User")
  }
  Say "Start-menu shortcut: $ShortcutPath"
}

# ---------------------------------------------------------------- smoke
if (-not $SkipSmoke) {
  Say "smoke test (emulator + mock backend, offscreen)"
  Invoke-Checked $VPy @((Join-Path $AppRoot "scripts\smoke.py"), "--seconds", "5")
}

Say "done. Start from the Start menu or: $Launcher   (add --emulator for a hardware-free demo)"
Warn "hardware scans need the Glasgow board bound to WinUSB (Zadig) once per PC"
