import os
import sysconfig
from pathlib import Path
from types import SimpleNamespace

import pytest

from GlasgowDataIO.IobeamControl.glasgowLib.glasgow.hardware.build_plan import (
    GatewareBuildError, GlasgowBuildPlan,
    ToolchainBuildPlan,
)


@pytest.mark.skipif(os.name != 'nt', reason='Exercises the actual Windows command interpreter')
def test_uncached_windows_build_uses_batch_script(tmp_path):
    inner = SimpleNamespace(script='build_top', files={
        'build_top.sh': 'exit 99\n',
        'build_top.bat': '@echo off\n>top.bin echo bitstream\nexit /b 0\n',
    })
    plan = GlasgowBuildPlan(inner, SimpleNamespace(env_vars={}))
    bitstream, output = plan.execute(tmp_path / 'build with spaces', debug=True)
    assert bitstream.strip() == b'bitstream'


@pytest.mark.skipif(os.name != 'nt', reason='Exercises the actual Windows command interpreter')
def test_windows_build_preserves_failure_exit_code(tmp_path):
    inner = SimpleNamespace(script='build_top', files={
        'build_top.bat': '@echo off\necho tool failed\nexit /b 7\n',
    })
    plan = GlasgowBuildPlan(inner, SimpleNamespace(env_vars={}))
    with pytest.raises(GatewareBuildError, match='exit code 7'):
        plan.execute(tmp_path / 'failed build', debug=True)


def test_extract_preserves_generated_text_and_binary_bytes(tmp_path):
    rtlil = '# Generated by Amaranth\nattribute \\top 1\nmodule \\top\nend\n'
    inner = SimpleNamespace(script='build_top', files={
        'build_top.sh': 'exit 0\n', 'build_top.bat': 'exit /b 0\n',
        'top.il': rtlil, 'binary': b'\x00\xff\n',
    })
    ToolchainBuildPlan(inner).extract(tmp_path)
    assert (tmp_path / 'top.il').read_bytes() == rtlil.encode('utf-8')
    assert (tmp_path / 'binary').read_bytes() == b'\x00\xff\n'


@pytest.mark.skipif(os.name != 'nt', reason='Exercises the actual Windows Yosys build')
def test_windows_yosys_parses_generated_rtlil(tmp_path):
    yosys = Path(sysconfig.get_path('scripts')) / 'yowasp-yosys.exe'
    if not yosys.is_file():
        pytest.skip('yowasp-yosys is not installed')
    rtlil = '# Generated by Amaranth\nattribute \\top 1\nmodule \\top\nend\n'
    inner = SimpleNamespace(script='build_top', files={
        'top.il': rtlil,
        'build_top.bat': '@echo off\n"%YOSYS%" -Q -p "read_rtlil top.il" || exit /b\n>top.bin echo parsed\nexit /b 0\n',
    })
    plan = GlasgowBuildPlan(inner, SimpleNamespace(env_vars={'YOSYS': str(yosys)}))
    bitstream, _ = plan.execute(tmp_path / 'yosys build', debug=True)
    assert bitstream.strip() == b'parsed'
    assert (tmp_path / 'yosys build' / 'top.il').read_bytes() == rtlil.encode('utf-8')
