M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Mon Sep 28 02:57:55 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T02:57:55+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.5Y156.5
X3.5Y3.5
X191.5Y156.5
X191.5Y3.5
M30
