from amaranth import *
from amaranth.build import *
from amaranth.lib import wiring
from amaranth.lib.wiring import In, Out, flipped
from amaranth.build import *
from ..commands.low_level_commands import DwellTime
from .fastBusController import FastBusController
from .supersampler import Supersampler
from .busController import BusController
from .rasterScanner import RasterScanner
from ..commands.low_level_commands import Command
from ..commands.structs import CmdType, BeamType, OutputMode, Transforms
from . import * # StreamSignature, BusSignature, BlankRequest, Transforms, DACStream

class CommandExecutor(wiring.Component):
    cmd_stream: In(StreamSignature(Command)) # type: ignore
    img_stream: Out(StreamSignature(unsigned(16)))# type: ignore

    bus: Out(BusSignature)# type: ignore
    inline_blank: In(BlankRequest)# type: ignore

    #: Active if `Synchronize`, `Flush`, or `Abort` was the last received command.
    flush: Out(1) # type: ignore

    # Input to Scan/Signal Selector Relay Board
    ext_ctrl_enable: Out(2) # type: ignore
    ext_ctrl_enabled: Out(2) # type: ignore
    beam_type: Out(BeamType) # type: ignore
    # Input to Blanking control board
    blank_enable: Out(1, init=1) # type: ignore

    #Input to Serializer
    output_mode: Out(2) # type: ignore


    def __init__(self, *, out_only:bool=False, adc_latency=8,
                adc_half_period=4, adc_settle_cycles=2,
                ext_switch_delay=960000,
                transforms: Transforms=Transforms(False, False, False)):
        self.adc_latency = adc_latency
        self.adc_half_period = adc_half_period
        self.adc_settle_cycles = adc_settle_cycles
        # Time for external control relay/switch to actuate
        self.ext_switch_delay = ext_switch_delay
        self.transforms = transforms

        self.supersampler = Supersampler()
        self.dac_x_code_transformed = Signal(14)
        self.dac_y_code_transformed = Signal(14)

        self.out_only = out_only
        super().__init__()

    def elaborate(self, platform):
        m = Module()

        delay_counter = Signal(16)
        inline_delay_counter = Signal(3)

        ext_switch_delay_counter = Signal(24)

        if self.out_only:
            m.submodules.bus_controller = bus_controller = FastBusController()
        else:
            m.submodules.bus_controller = bus_controller = BusController(
                adc_half_period=self.adc_half_period,
                adc_latency=self.adc_latency,
                adc_settle_cycles=self.adc_settle_cycles,
                transforms=self.transforms)
        m.submodules.raster_scanner = self.raster_scanner = RasterScanner()
        m.submodules.supersampler = self.supersampler

        if not self.out_only:
            m.d.comb += [
                self.dac_x_code_transformed.eq(bus_controller.dac_x_code_transformed),
                self.dac_y_code_transformed.eq(bus_controller.dac_y_code_transformed),
            ]

        wiring.connect(m, self.supersampler.super_dac_stream, bus_controller.dac_stream)
        wiring.connect(m, bus_controller.adc_stream, self.supersampler.super_adc_stream)
        wiring.connect(m, flipped(self.bus), bus_controller.bus)
        m.d.comb += self.inline_blank.eq(bus_controller.inline_blank)

        vector_stream = StreamSignature(DACStream).create()

        raster_mode = Signal()
        output_mode = Signal(2)
        command = Signal.like(self.cmd_stream.payload)

        # ------------------------------------------------------------------ #
        # FIX: Drive self.output_mode at module level so it is valid in ALL
        # FSM states, including Write_FFFF and Write_cookie.
        # Previously this was only driven inside the "Imaging" state, which
        # meant output_mode defaulted to 0 (NoOutput) during the sync cookie
        # write states — causing the serializer to silently discard the response.
        # ------------------------------------------------------------------ #
        m.d.comb += self.output_mode.eq(output_mode)

        with m.If(raster_mode):
            wiring.connect(m, self.raster_scanner.dac_stream, self.supersampler.dac_stream)
        with m.Else():
            wiring.connect(m, vector_stream, self.supersampler.dac_stream)

        in_flight_pixels = Signal(4)
        submit_pixel = Signal()
        retire_pixel = Signal()
        m.d.sync += in_flight_pixels.eq(in_flight_pixels + submit_pixel - retire_pixel)

        next_blank_enable = Signal(reset=1)
        # `bus.dac_clk` is generated by sync-domain logic in BusController.
        # Treating it as a local clock domain creates a generated-clock CDC
        # when `blank_enable` is consumed by the rest of the sync-domain design.
        # Keep blanking state in sync; the DAC clock remains only an output
        # strobe to the analog board.
        m.d.sync += self.blank_enable.eq(next_blank_enable)

        sync_blank = Signal(BlankRequest)
        with m.If(submit_pixel):
            m.d.sync += sync_blank.request.eq(0)
        async_blank = Signal(BlankRequest)

        with m.If(self.inline_blank.request):
            m.d.sync += next_blank_enable.eq(self.inline_blank.enable)
        with m.Else():
            with m.If(async_blank.request):
                m.d.sync += next_blank_enable.eq(async_blank.enable)
                m.d.sync += async_blank.request.eq(0)

        run_length = Signal.like(command.payload.raster_pixel_run.length)
        raster_region = Signal.like(command.payload.raster_region.roi)
        m.d.comb += [
            self.raster_scanner.roi_stream.payload.eq(raster_region),
            vector_stream.payload.dac_x_code.eq(command.payload.vector_pixel.x_coord),
            vector_stream.payload.dac_y_code.eq(command.payload.vector_pixel.y_coord),
            vector_stream.payload.dwell_time.eq(command.payload.vector_pixel.dwell_time)
        ]

        sync_req = Signal()
        sync_ack = Signal()

        self.is_executing = Signal()
        with m.FSM() as fsm:
            m.d.comb += self.is_executing.eq(fsm.ongoing("Execute"))
            with m.State("Fetch"):
                m.d.comb += self.cmd_stream.ready.eq(1)
                with m.If(self.cmd_stream.valid):
                    m.d.sync += command.eq(self.cmd_stream.payload)
                    m.next = "Execute"

            with m.State("Execute"):
                m.d.sync += self.flush.eq(0)

                with m.Switch(command.type):
                    with m.Case(CmdType.Synchronize):
                        m.d.sync += self.flush.eq(1)
                        # -------------------------------------------------- #
                        # FIX: Update output_mode HERE, before sync_ack, so
                        # the new mode is already latched when Write_FFFF and
                        # Write_cookie run. Previously this was updated after
                        # sync_ack, meaning the first sync always used the
                        # old mode (0 = NoOutput) during the cookie write.
                        # -------------------------------------------------- #
                        m.d.sync += output_mode.eq(command.payload.synchronize.mode.output)
                        m.d.comb += sync_req.eq(1)
                        with m.If(sync_ack):
                            m.next = "Fetch"

                    with m.Case(CmdType.Abort):
                        m.d.sync += self.flush.eq(1)
                        m.d.comb += self.raster_scanner.abort.eq(1)
                        m.next = "Fetch"

                    with m.Case(CmdType.Flush):
                        m.d.sync += self.flush.eq(1)
                        m.next = "Fetch"

                    with m.Case(CmdType.Delay):
                        with m.If(delay_counter == command.payload.delay.delay):
                            m.d.sync += delay_counter.eq(0)
                            m.next = "Fetch"
                        with m.Else():
                            m.d.sync += delay_counter.eq(delay_counter + 1)

                    with m.Case(CmdType.ExternalCtrl):
                        with m.If(self.supersampler.dac_stream.ready):
                            m.d.sync += self.ext_ctrl_enable.eq(command.payload.external_ctrl.enable)
                            with m.If(command.payload.external_ctrl.enable):
                                m.d.sync += self.ext_ctrl_enabled.eq(1)
                            with m.If(ext_switch_delay_counter == self.ext_switch_delay):
                                m.d.sync += ext_switch_delay_counter.eq(0)
                                with m.If(~command.payload.external_ctrl.enable):
                                    m.d.sync += self.ext_ctrl_enabled.eq(0)
                                m.next = "Fetch"
                            with m.Else():
                                m.d.sync += ext_switch_delay_counter.eq(ext_switch_delay_counter + 1)

                    with m.Case(CmdType.BeamSelect):
                        with m.If(self.supersampler.dac_stream.ready):
                            m.d.sync += self.beam_type.eq(command.payload.beam_select.beam_type)
                            m.next = "Fetch"

                    with m.Case(CmdType.Blank):
                        with m.If(command.payload.blank.inline):
                            m.d.sync += sync_blank.enable.eq(command.payload.blank.enable)
                            m.d.sync += sync_blank.request.eq(1)
                            m.next = "Fetch"
                        with m.Else():
                            with m.If(self.supersampler.dac_stream.ready):
                                m.d.sync += async_blank.enable.eq(command.payload.blank.enable)
                                m.d.sync += async_blank.request.eq(1)
                                m.next = "Fetch"

                    with m.Case(CmdType.RasterRegion):
                        m.d.comb += raster_mode.eq(1)
                        m.d.sync += raster_region.eq(command.payload.raster_region.roi)
                        m.d.comb += [
                            self.raster_scanner.roi_stream.valid.eq(1),
                            self.raster_scanner.roi_stream.payload.eq(command.payload.raster_region.roi),
                        ]
                        m.d.comb += self.raster_scanner.abort.eq(1)
                        with m.If(self.raster_scanner.roi_stream.ready):
                            m.next = "Fetch"

                    with m.Case(CmdType.RasterPixel):
                        m.d.comb += raster_mode.eq(1)
                        m.d.comb += [
                            self.raster_scanner.dwell_stream.valid.eq(1),
                            self.raster_scanner.dwell_stream.payload.dwell_time.eq(command.payload.raster_pixel.dwell_time),
                            self.raster_scanner.dwell_stream.payload.blank.eq(sync_blank)
                        ]
                        with m.If(self.raster_scanner.dwell_stream.ready):
                            m.d.comb += submit_pixel.eq(1)
                            m.next = "Fetch"

                    with m.Case(CmdType.RasterPixelRun):
                        m.d.comb += raster_mode.eq(1)
                        m.d.comb += [
                            self.raster_scanner.dwell_stream.valid.eq(1),
                            self.raster_scanner.dwell_stream.payload.dwell_time.eq(command.payload.raster_pixel_run.dwell_time),
                            self.raster_scanner.dwell_stream.payload.blank.eq(sync_blank)
                        ]
                        with m.If(self.raster_scanner.dwell_stream.ready):
                            m.d.comb += submit_pixel.eq(1)
                            with m.If(run_length == command.payload.raster_pixel_run.length):
                                m.d.sync += run_length.eq(0)
                                m.next = "Fetch"
                            with m.Else():
                                m.d.sync += run_length.eq(run_length + 1)

                    with m.Case(CmdType.RasterPixelFill):
                        m.d.comb += raster_mode.eq(1)
                        with m.If(self.raster_scanner.dwell_stream.ready):
                            m.d.comb += submit_pixel.eq(1)
                        with m.If(self.raster_scanner.roi_stream.ready):
                            m.next = "Fetch"
                        with m.Else():
                            m.d.comb += [
                                self.raster_scanner.dwell_stream.valid.eq(1),
                                self.raster_scanner.dwell_stream.payload.dwell_time.eq(command.payload.raster_pixel_fill.dwell_time),
                                self.raster_scanner.dwell_stream.payload.blank.eq(sync_blank)
                            ]

                    with m.Case(CmdType.RasterPixelFreeRun):
                        m.d.comb += raster_mode.eq(1)
                        m.d.comb += [
                            self.raster_scanner.roi_stream.payload.eq(raster_region),
                            self.raster_scanner.dwell_stream.payload.dwell_time.eq(command.payload.raster_pixel.dwell_time),
                            self.raster_scanner.dwell_stream.payload.blank.eq(sync_blank)
                        ]
                        with m.If(self.cmd_stream.valid):
                            m.d.comb += self.raster_scanner.abort.eq(1)
                            with m.If(in_flight_pixels == 0):
                                m.next = "Fetch"
                        with m.Else():
                            m.d.comb += self.raster_scanner.roi_stream.valid.eq(1)
                            m.d.comb += self.raster_scanner.dwell_stream.valid.eq(1)
                            with m.If(self.raster_scanner.dwell_stream.ready):
                                m.d.comb += submit_pixel.eq(1)

                    with m.Case(CmdType.VectorPixel, CmdType.VectorPixelMinDwell):
                        m.d.comb += vector_stream.valid.eq(1)
                        m.d.comb += vector_stream.payload.blank.eq(sync_blank)
                        m.d.comb += vector_stream.payload.delay.eq(inline_delay_counter)
                        with m.If(vector_stream.ready):
                            m.d.sync += inline_delay_counter.eq(0)
                            m.d.comb += submit_pixel.eq(1)
                            m.next = "Fetch"

        with m.FSM():
            with m.State("Imaging"):
                m.d.comb += [
                    self.img_stream.payload.eq(self.supersampler.adc_stream.payload.adc_code),
                    self.img_stream.valid.eq(self.supersampler.adc_stream.valid),
                    self.supersampler.adc_stream.ready.eq(self.img_stream.ready),
                    # output_mode assignment removed from here — now driven at module level above
                ]
                if self.out_only:
                    m.d.comb += retire_pixel.eq(submit_pixel)
                else:
                    m.d.comb += retire_pixel.eq(self.supersampler.adc_stream.valid & self.img_stream.ready)
                with m.If((in_flight_pixels == 0) & sync_req):
                    m.next = "Write_FFFF"

            with m.State("Write_FFFF"):
                m.d.comb += [
                    self.img_stream.payload.eq(0xffff),
                    self.img_stream.valid.eq(1),
                ]
                with m.If(self.img_stream.ready):
                    m.next = "Write_cookie"

            with m.State("Write_cookie"):
                m.d.comb += [
                    self.img_stream.payload.eq(command.payload.synchronize.cookie),
                    self.img_stream.valid.eq(1),
                ]
                with m.If(self.img_stream.ready):
                    m.d.comb += sync_ack.eq(1)
                    m.next = "Imaging"

        return m
